# screen
screen_settings:
  - domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
  - domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0
  - domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true

# trackpad
trackpad_settings:
  # Disable Natural scroll
  - domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: int
    value: 0

# finder
finder_settings:
  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  - domain: com.apple.finder
    key: FinderSounds
    type: bool
    value: false
  - domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true
  - domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  - domain: com.apple.finder
    key: ShowTabView
    type: bool
    value: true
  - domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  # show full path on title bar
  - domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true
  # keep folder top on sort
  - domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
  # search the current folder by default
  - domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf
  # no worning on change extentions
  - domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  # Avoid creating .DS_Store files on network or USB volumes
  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  - domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true
  # Use list view in all Finder windows by default
  # Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
  - domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv

# dock
dock_settings:
  # Minimize windows into their application’s icon
  - domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
  # Show indicator lights for open applications in the Dock
  - domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true

# terminal
terminal_settings:
  # Use utf-8
  - domain: com.apple.terminal
    key: StringEncodings
    type: array
    value: 4
