# https://github.com/lukesampson/scoop/tree/master/bucket
- name: "Install linux tools"
  scoop_install:
    state: present
    name:
      - cmake
      - gcc
      - gow
      - jq
      - sudo
      - time
      - unzip

- name: "Install windows tools"
  scoop_install:
    state: present
    name:
      - 7zip
      - aws
      - bat
      - chromedriver
      - git
      - git-lfs
      - ngrok
      - pwsh
      - terraform
      - gibo

- name: "Install Programming Languages"
  scoop_install:
    state: present
    name:
      - go
      - nvm
