---
# "ansible_home" may be: /home/guitarrapc
- name: "env.Home"
  ansible.builtin.debug:
    var: ansible_env.HOME
- name: "become env.HOME"
  become: true
  ansible.builtin.debug:
    var: ansible_env.HOME

# "ansible_user" should be `ubuntu`
- name: "ansible_user_id"
  ansible.builtin.debug:
    var: ansible_user_id
- name: "become ansible_user_id"
  become: true
  ansible.builtin.debug:
    var: ansible_user_id
- name: "ansible_ssh_user"
  ansible.builtin.debug:
    var: ansible_ssh_user

# "ansible_distribution" may be: "Debian", "SLES", "Ubuntu", "CentOS"
# "ansible_distribution_version" may be: "9.0", "12.2", "18.04", "7.3.1611"
# "ansible_distribution_major_version" may be: "9", "12", 18.04"
# "ansible_distribution_release" may be: "bionic"
# "ansible_os_family" may be: "Debian", "RedHat", "Suse"
# Upper/lower case is important, you can change UPPER or lower via `|uppper` or `|lower`
- name: "distribution"
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }}"
- name: "distribution lower case"
  ansible.builtin.debug:
    msg: "{{ ansible_distribution|lower }}"
- name: "distribution version"
  ansible.builtin.debug:
    msg: "{{ ansible_distribution_version }}"
- name: "distribution release"
  ansible.builtin.debug:
    msg: "{{ ansible_distribution_release }}"
