apt_tools:
  - apache2-utils
  - direnv
  # - duf # not available below 22.04
  - fd-find
  - git-lfs
  - graphviz # require for terraform graph and ansible-playbook-graph
  - htop
  - hub
  - jq
  - moreutils
  - peco
  - pkg-config
  - python3-pip
  - sshpass
  - tree
  - unzip
  - whois

asdf: # https://github.com/asdf-vm/asdf
  version: v0.13.1

asdf_plugins:
  - name: argocd # https://github.com/argoproj/argo-cd
    source: https://github.com/beardix/asdf-argocd.git
    version_arg: "version --client"
    version: "2.8.6"
  - name: aws-vault # https://github.com/99designs/aws-vault
    source: https://github.com/virtualstaticvoid/asdf-aws-vault.git
    version_arg: "--version"
    version: "7.2.0"
  - name: awscli # see docker for specific release. https://github.com/aws/aws-cli
    source: https://github.com/MetricMike/asdf-awscli.git
    version_arg: "--version"
    version: "2.13.37"
  - name: bombardier # https://github.com/codesenberg/bombardier
    source: https://github.com/NeoHsu/asdf-bombardier.git
    version_arg: "--version"
    version: "1.2.6"
  - name: conftest # https://github.com/open-policy-agent/conftest
    source: https://github.com/dhoeric/asdf-conftest.git
    version_arg: "--version"
    version: "0.46.0"
  - name: ctop # https://github.com/bcicen/ctop
    source: https://github.com/neohsu/asdf-ctop.git
    version_arg: "-v"
    version: "0.7.7"
  - name: eksctl # https://github.com/eksctl-io/eksctl
    source: https://github.com/elementalvoid/asdf-eksctl.git
    version_arg: "version"
    version: "0.164.0"
  - name: github-cli # https://github.com/cli/cli
    source: https://github.com/bartlomiejdanek/asdf-github-cli.git
    version_arg: ""
    version: "2.39.1"
  - name: grpc-health-probe # https://github.com/grpc-ecosystem/grpc-health-probe
    source: https://github.com/zufardhiyaulhaq/asdf-grpc-health-probe.git
    version_arg: ""
    version: "0.4.22"
  - name: grpcurl # https://github.com/fullstorydev/grpcurl
    source: https://github.com/asdf-community/asdf-grpcurl.git
    version_arg: "--version"
    version: "1.8.9"
  - name: helm # https://github.com/helm/helm
    source: https://github.com/Antiarchitect/asdf-helm.git
    version_arg: "version --short"
    version: "3.13.2"
  - name: kubectl
    source: https://github.com/asdf-community/asdf-kubectl.git
    version_arg: "version --client --short"
    version: "1.29.0"
  - name: kustomize # https://github.com/kubernetes-sigs/kustomize
    source: https://github.com/Banno/asdf-kustomize.git
    version_arg: version
    version: "5.2.1"
  - name: lazygit # https://github.com/jesseduffield/lazygit
    source: https://github.com/nklmilojevic/asdf-lazygit.git
    version_arg: "--version"
    version: "0.40.2"
  - name: nodejs # https://nodejs.org/en/
    source: https://github.com/asdf-vm/asdf-nodejs.git
    version_arg: "--version"
    version: "20.9.0"
  - name: sops # https://github.com/getsops/sops
    source: https://github.com/feniix/asdf-sops.git
    version_arg: "--version"
    version: "3.8.1"
  - name: step # https://github.com/smallstep/cli
    source: https://github.com/log2/asdf-step.git
    version_arg: "--version"
    version: "0.25.0"
  - name: stern # https://github.com/stern/stern
    source: https://github.com/looztra/asdf-stern
    version_arg: "--version"
    version: "1.27.0"
  - name: terraform-docs # https://github.com/terraform-docs/terraform-docs
    source: https://github.com/looztra/asdf-terraform-docs
    version_arg: "--version"
    version: "0.16.0"
  - name: terraformer # https://github.com/GoogleCloudPlatform/terraformer
    source: https://github.com/jmcvetta/asdf-terraformer
    version_arg: "--version"
    version: "0.8.24"
  - name: tflint # https://github.com/terraform-linters/tflint
    source: https://github.com/skyzyx/asdf-tflint
    version_arg: "--version"
    version: "0.49.0"
  - name: yq # https://github.com/mikefarah/yq
    source: https://github.com/sudermanjr/asdf-yq.git
    version_arg: "--version"
    version: "4.40.2"

binary:
  - name: eks-node-viewer # `eks-node-viewer --version` https://github.com/awslabs/eks-node-viewer
    version_arg: "--version"
    version: "0.2.1"
    download_url: https://github.com/awslabs/eks-node-viewer/releases/download/v0.5.0/eks-node-viewer_Linux_x86_64
  - name: kubectl-argo-rollouts # `kubectl argo rollouts version` https://argoproj.github.io/argo-rollouts/installation/#kubectl-plugin-installation
    version_arg: "version"
    version: "1.6.2"
    download_url: https://github.com/argoproj/argo-rollouts/releases/download/v1.6.2/kubectl-argo-rollouts-linux-amd64
  - name: linkerd # `linkerd version --client` https://github.com/linkerd/linkerd2
    version_arg: "version --client"
    version: "2.12.0"
    download_url: https://github.com/linkerd/linkerd2/releases/download/stable-2.14.4/linkerd2-cli-stable-2.14.4-linux-amd64

binary_archive:
  - name: cert
    version_arg: "-v"
    version: "1.0.0"
    download_url: https://github.com/genkiroid/cert/releases/download/1.0.0/cert_1.0.0_linux_64bit.tar.gz
    copy_root: ""
    binaries:
      - cert
  - name: circleci # https://github.com/CircleCI-Public/circleci-cli
    version_arg: "version"
    version: "0.1.29314"
    download_url: https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.29314/circleci-cli_0.1.29314_linux_amd64.tar.gz
    copy_root: "circleci-cli_0.1.29314_linux_amd64/"
    binaries:
      - circleci
  - name: pulumi # https://github.com/pulumi/pulumi
    version_arg: "version"
    version: "v3.94.2"
    download_url: https://get.pulumi.com/releases/sdk/pulumi-v3.90.0-linux-x64.tar.gz
    copy_root: "pulumi/"
    binaries:
      - pulumi
      - pulumi-analyzer-policy
      - pulumi-analyzer-policy-python
      - pulumi-language-dotnet
      - pulumi-language-go
      - pulumi-language-java
      - pulumi-language-nodejs
      - pulumi-language-python
      - pulumi-language-python-exec
      - pulumi-language-yaml
      - pulumi-resource-pulumi-nodejs
      - pulumi-resource-pulumi-python
      - pulumi-watch
  - name: tldr # https://github.com/isacikgoz/tldr
    version_arg: "--version"
    version: "0.6.1"
    download_url: https://github.com/isacikgoz/tldr/releases/download/v0.6.1/tldr_0.6.1_linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - tldr
  - name: trivy # https://github.com/aquasecurity/trivy
    version_arg: "--version"
    version: "0.47.0"
    download_url: https://github.com/aquasecurity/trivy/releases/download/v0.47.0/trivy_0.47.0_Linux-64bit.tar.gz
    copy_root: ""
    binaries:
      - trivy

dotnet:
  version: "8.0"

dpkg_install:
  - name: session-manager-plugin # https://github.com/aws/session-manager-plugin
    version_arg: "--version"
    version: "1.2.497.0"
    download_url: https://s3.amazonaws.com/session-manager-downloads/plugin/1.2.398.0/ubuntu_64bit/session-manager-plugin.deb

git_tools:
  - name: kubectx
    git_https_url: https://github.com/ahmetb/kubectx.git
    link_binaries:
      - kubectx
      - kubens
  - name: kube-ps1
    git_https_url: https://github.com/jonmosco/kube-ps1.git

go:
  version: "go" # install latest

homebrew:
  - packages:
      - { name: "hello", state: "present" }

krew: # https://github.com/kubernetes-sigs/krew
  version: "0.4.4"

krew_plugins:
  - name: explore # https://github.com/keisku/kubectl-explore A better kubectl explain with the fuzzy finder
    install_check_arg: "--help"
  - name: fuzzy # https://github.com/d-kuro/kubectl-fuzzy Instead of specifying full resource names to kubectl commands, you can choose them from an interactive list that you can filter by typing a few characters.
    install_check_arg: "--help"
  - name: get-all # https://github.com/corneliusweig/ketall Like `kubectl get all`, but get really all resources
    install_check_arg: "--help"
  - name: iexec # https://github.com/gabeduke/kubectl-iexec Kubectl plugin to interactively exec into a pod
    install_check_arg: "--help"
  - name: images # https://github.com/chenjiandongx/kubectl-images Show container images used in the cluster.
    install_check_arg: "--help"
  - name: lineage # https://github.com/tohjustin/kube-lineage display all dependencies or dependents of an object in a Kubernetes cluster
    install_check_arg: "--help"
  - name: ktop # https://github.com/vladimirvivien/ktop A top-like tool for your Kubernetes clusters
    install_check_arg: "--help"
  - name: neat # https://github.com/itaysk/kubectl-neat Clean up Kubernetes yaml and json output to make it readable
    install_check_arg: "--help"
  - name: resource-capacity # https://github.com/robscott/kube-capacity A simple CLI that provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster
    install_check_arg: "--help"
  - name: rolesum # https://github.com/Ladicle/kubectl-rolesum Summarize Kubernetes RBAC roles for the specified subjects.
    install_check_arg: "--help"
  - name: view-secret # https://github.com/elsesiy/kubectl-view-secret Kubernetes CLI plugin to decode Kubernetes secrets
    install_check_arg: "--help"
  - name: who-can # https://github.com/aquasecurity/kubectl-who-can Show who has RBAC permissions to perform actions on different resources in Kubernetes
    install_check_arg: "--help"

pip_tools:
  - name: ansible-lint # https://github.com/ansible/ansible-lint
    version: "6.22.0"
  - name: ansible-playbook-grapher # require: graphviz https://github.com/haidaraM/ansible-playbook-grapher
    version: "2.1.0"

terraform: # https://github.com/hashicorp/terraform
  version: "1.5.6"
  force_symlink: true
