apt_tools:
  - apache2-utils
  - direnv
  # - duf # not available below 22.04
  - fd-find
  - git-lfs
  - htop
  - hub
  - jq
  - moreutils
  - peco
  - pkg-config
  - python3-pip
  - sshpass
  - tree
  - unzip
  - whois

binary_install:
  - name: argocd
    version_arg: "version --client"
    version: "2.4.11"
    download_url: https://github.com/argoproj/argo-cd/releases/download/v2.4.11/argocd-linux-amd64
  - name: aws-vault
    version_arg: "--version"
    version: "6.6.0"
    download_url: https://github.com/99designs/aws-vault/releases/download/v6.6.0/aws-vault-linux-amd64
  - name: bombardier
    version_arg: "--version"
    version: "1.2.5"
    download_url: https://github.com/codesenberg/bombardier/releases/download/v1.2.5/bombardier-linux-amd64
  - name: ctop
    version_arg: "-v"
    version: "0.7.7"
    download_url: https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64
  - name: grpc_health_probe
    checksum_type: sha256sum
    checksum: cc7e5f4eeafb4936838448dd767dbb8cd6bab7ebe25ce3803b00c2079a68c8a8
    download_url: https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.12/grpc_health_probe-linux-amd64
  - name: linkerd
    version_arg: "version --client"
    version: "2.12.0"
    download_url: https://github.com/linkerd/linkerd2/releases/download/stable-2.12.0/linkerd2-cli-stable-2.12.0-linux-amd64
  - name: kubectl
    version_arg: "version --client --short"
    version: "1.24.8"
    download_url: https://storage.googleapis.com/kubernetes-release/release/v1.24.8/bin/linux/amd64/kubectl
  - name: sops
    version_arg: "--version"
    version: "3.7.3"
    download_url: https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux
  - name: stern
    version_arg: "--version"
    version: "1.11.0"
    download_url: https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64

dpkg_install:
  - name: session-manager-plugin
    version_arg: "--version"
    version: "1.2.398.0"
    download_url: https://s3.amazonaws.com/session-manager-downloads/plugin/1.2.398.0/ubuntu_64bit/session-manager-plugin.deb

targz_binary_install:
  - name: cert
    version_arg: "-v"
    version: "0.15.0"
    download_url: https://github.com/genkiroid/cert/releases/download/0.15.0/cert_0.15.0_linux_64bit.tar.gz
    copy_root: ""
    binaries:
      - cert
  - name: circleci
    version_arg: "version"
    version: "0.1.22426"
    download_url: https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.22426/circleci-cli_0.1.22426_linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - circleci
  - name: conftest
    version_arg: "-v"
    version: "0.34.0"
    download_url: https://github.com/open-policy-agent/conftest/releases/download/v0.34.0/conftest_0.34.0_Linux_x86_64.tar.gz
    copy_root: ""
    binaries:
      - conftest
  - name: eksctl
    version_arg: "version"
    version: "0.111.0"
    download_url: https://github.com/weaveworks/eksctl/releases/download/v0.111.0/eksctl_Linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - eksctl
  - name: grpcurl
    version_arg: "--version"
    version: "1.8.7"
    download_url: https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz
    copy_root: ""
    binaries:
      - grpcurl
  - name: helm
    version_arg: "version --short"
    version: "3.9.4"
    download_url: https://get.helm.sh/helm-v3.9.4-linux-amd64.tar.gz
    copy_root: linux-amd64/
    binaries:
      - helm
  - name: lazygit
    version_arg: "--version"
    version: "0.35"
    download_url: https://github.com/jesseduffield/lazygit/releases/download/v0.35/lazygit_0.35_Linux_x86_64.tar.gz
    copy_root: ""
    binaries:
      - lazygit
  - name: step
    version_arg: "--version"
    version: "0.22.0"
    download_url: https://github.com/smallstep/cli/releases/download/v0.22.0/step_linux_0.22.0_amd64.tar.gz
    copy_root: "step_0.22.0/bin/"
    binaries:
      - step
    dest_override: /usr/bin/
  - name: tldr
    version_arg: "--version"
    version: "0.6.1"
    download_url: https://github.com/isacikgoz/tldr/releases/download/v0.6.1/tldr_0.6.1_linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - tldr
  - name: yq
    version_arg: "--version"
    version: "4.27.5"
    download_url: https://github.com/mikefarah/yq/releases/download/v4.27.5/yq_linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - yq_linux_amd64
    dest_override: /usr/local/bin/yq # rename to yq

git_tools:
  - name: kubectx
    git_https_url: https://github.com/ahmetb/kubectx.git
    link_binaries:
      - kubectx
      - kubens
  - name: kube-ps1
    git_https_url: https://github.com/jonmosco/kube-ps1.git

homebrew:
  - packages:
      - { name: "hello", state: "present" }

anyenv:
  - goenv: "false"
    nodenv: "true"
    pyenv: "false"

aws_cli:
  - version: "2.8.13"

dotnet_tools:
  - dotnet-sdk-6.0

dotnet:
  - version: "6.0"

gh_cli:
  - version: "2.10.1"

krew:
  - version: "0.4.3"

kubectl_plugin:
  - name: explore
    install_check_arg: "--help"
  - name: fuzzy
    install_check_arg: "--help"
  - name: get-all
    install_check_arg: "--help"
  - name: iexec
    install_check_arg: "--help"
  - name: images
    install_check_arg: "--help"
  - name: neat
    install_check_arg: "--help"
  - name: resource-capacity
    install_check_arg: "--help"
  - name: rolesum
    install_check_arg: "--help"
  - name: view-secret
    install_check_arg: "--help"
  - name: who-can
    install_check_arg: "--help"

terraform:
  - version: "1.3.4"
