apt_tools:
  - apache2-utils
  - direnv
  # - duf # not available below 22.04
  - fd-find
  - git-lfs
  - graphviz #require for terraform graph and ansible-playbook-graph
  - htop
  - hub
  - jq
  - moreutils
  - peco
  - pkg-config
  - python3-pip
  - sshpass
  - tree
  - unzip
  - whois
  # trivy requirements
  - apt-transport-https
  - lsb-release

asdf:
  version: v0.11.1

asdf_plugins:
  - name: argocd
    source: https://github.com/beardix/asdf-argocd.git
    version_arg: "version --client"
    version: "2.6.6"
  - name: aws-vault
    source: https://github.com/virtualstaticvoid/asdf-aws-vault.git
    version_arg: "--version"
    version: "6.6.2"
  - name: awscli
    source: https://github.com/MetricMike/asdf-awscli.git
    version_arg: "--version"
    version: "2.9.22"
  - name: bombardier
    source: https://github.com/NeoHsu/asdf-bombardier.git
    version_arg: "--version"
    version: "1.2.5"
  - name: conftest
    source: https://github.com/dhoeric/asdf-conftest.git
    version_arg: "--version"
    version: "0.39.0"
  - name: ctop
    source: https://github.com/neohsu/asdf-ctop.git
    version_arg: "-v"
    version: "0.7.7"
  - name: eksctl
    source: https://github.com/elementalvoid/asdf-eksctl.git
    version_arg: "version"
    version: "0.129.0"
  - name: github-cli
    source: https://github.com/bartlomiejdanek/asdf-github-cli.git
    version_arg: ""
    version: "2.23.0"
  - name: grpc-health-probe
    source: https://github.com/zufardhiyaulhaq/asdf-grpc-health-probe.git
    version_arg: ""
    version: "0.4.15"
  - name: grpcurl
    source: https://github.com/asdf-community/asdf-grpcurl.git
    version_arg: "--version"
    version: "1.8.7"
  - name: helm
    source: https://github.com/Antiarchitect/asdf-helm.git
    version_arg: "version --short"
    version: "3.11.1"
  - name: kubectl
    source: https://github.com/asdf-community/asdf-kubectl.git
    version_arg: "version --client --short"
    version: "1.25.6"
  - name: kustomize
    source: https://github.com/Banno/asdf-kustomize.git
    version_arg: version
    version: "5.0.1"
  - name: lazygit
    source: https://github.com/nklmilojevic/asdf-lazygit.git
    version_arg: "--version"
    version: "0.37.0"
  - name: nodejs
    source: https://github.com/asdf-vm/asdf-nodejs.git
    version_arg: "--version"
    version: "19.6.0"
  - name: sops
    source: https://github.com/feniix/asdf-sops.git
    version_arg: "--version"
    version: "3.7.3"
  - name: step
    source: https://github.com/log2/asdf-step.git
    version_arg: "--version"
    version: "0.23.2"
  - name: stern
    source: https://github.com/looztra/asdf-stern
    version_arg: "--version"
    version: "1.23.0"
  - name: terraform-docs
    source: https://github.com/looztra/asdf-terraform-docs
    version_arg: "--version"
    version: "0.16.0"
  - name: terraformer
    source: https://github.com/jmcvetta/asdf-terraformer
    version_arg: "--version"
    version: "0.8.24"
  - name: tflint
    source: https://github.com/skyzyx/asdf-tflint
    version_arg: "--version"
    version: "0.45.0"
  - name: yq
    source: https://github.com/sudermanjr/asdf-yq.git
    version_arg: "--version"
    version: "4.30.8"

binary_install:
  - name: eks-node-viewer
    version_arg: "--version"
    version: "0.2.1"
    download_url: https://github.com/awslabs/eks-node-viewer/releases/download/v0.2.1/eks-node-viewer_Linux_x86_64
  - name: linkerd
    version_arg: "version --client"
    version: "2.12.0"
    download_url: https://github.com/linkerd/linkerd2/releases/download/stable-2.12.0/linkerd2-cli-stable-2.12.0-linux-amd64

dotnet:
  version: "dotnet-sdk-6.0"

dpkg_install:
  - name: session-manager-plugin
    version_arg: "--version"
    version: "1.2.398.0"
    download_url: https://s3.amazonaws.com/session-manager-downloads/plugin/1.2.398.0/ubuntu_64bit/session-manager-plugin.deb
  - name: trivy
    version_arg: "--version"
    version: "0.18.3"
    download_url: https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb

git_tools:
  - name: kubectx
    git_https_url: https://github.com/ahmetb/kubectx.git
    link_binaries:
      - kubectx
      - kubens
  - name: kube-ps1
    git_https_url: https://github.com/jonmosco/kube-ps1.git

homebrew:
  - packages:
      - { name: "hello", state: "present" }

krew:
  version: "0.4.3"

krew_plugins:
  - name: explore # https://github.com/keisku/kubectl-explore A better kubectl explain with the fuzzy finder
    install_check_arg: "--help"
  - name: fuzzy # https://github.com/d-kuro/kubectl-fuzzy Instead of specifying full resource names to kubectl commands, you can choose them from an interactive list that you can filter by typing a few characters.
    install_check_arg: "--help"
  - name: get-all # https://github.com/corneliusweig/ketall Like `kubectl get all`, but get really all resources
    install_check_arg: "--help"
  - name: iexec # https://github.com/gabeduke/kubectl-iexec Kubectl plugin to interactively exec into a pod
    install_check_arg: "--help"
  - name: images # https://github.com/chenjiandongx/kubectl-images Show container images used in the cluster.
    install_check_arg: "--help"
  - name: lineage # https://github.com/tohjustin/kube-lineage display all dependencies or dependents of an object in a Kubernetes cluster
    install_check_arg: "--help"
  - name: ktop # https://github.com/vladimirvivien/ktop A top-like tool for your Kubernetes clusters
    install_check_arg: "--help"
  - name: neat # https://github.com/itaysk/kubectl-neat Clean up Kubernetes yaml and json output to make it readable
    install_check_arg: "--help"
  - name: resource-capacity # https://github.com/robscott/kube-capacity A simple CLI that provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster
    install_check_arg: "--help"
  - name: rolesum # https://github.com/Ladicle/kubectl-rolesum Summarize Kubernetes RBAC roles for the specified subjects.
    install_check_arg: "--help"
  - name: view-secret # https://github.com/elsesiy/kubectl-view-secret Kubernetes CLI plugin to decode Kubernetes secrets
    install_check_arg: "--help"
  - name: who-can # https://github.com/aquasecurity/kubectl-who-can Show who has RBAC permissions to perform actions on different resources in Kubernetes
    install_check_arg: "--help"

pip_tools:
  - name: ansible-lint
    version: "6.16.1"
  - name: ansible-playbook-grapher # require: graphviz
    version: "2.0.0"

targz_binary_install:
  - name: cert
    version_arg: "-v"
    version: "0.15.0"
    download_url: https://github.com/genkiroid/cert/releases/download/0.15.0/cert_0.15.0_linux_64bit.tar.gz
    copy_root: ""
    binaries:
      - cert
  - name: circleci
    version_arg: "version"
    version: "0.1.22426"
    download_url: https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.22426/circleci-cli_0.1.22426_linux_amd64.tar.gz
    copy_root: "circleci-cli_0.1.22426_linux_amd64/"
    binaries:
      - circleci
  - name: tldr
    version_arg: "--version"
    version: "0.6.1"
    download_url: https://github.com/isacikgoz/tldr/releases/download/v0.6.1/tldr_0.6.1_linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - tldr

terraform:
  version: "1.3.4"
  force_symlink: true
