apt_tools:
  - apache2-utils
  - direnv
  - git-lfs
  - jq
  - moreutils
  - peco
  - pkg-config
  - python3-pip
  - sshpass
  - tree
  - unzip

binary_install:
  - name: argocd
    enable: "1"
    version_arg: "version"
    version: "1.8.7"
    download_url: https://github.com/argoproj/argo-cd/releases/download/v1.8.7/argocd-linux-amd64
  - name: bombardier
    enable: "1"
    version_arg: "--version"
    version: "1.2.4"
    download_url: https://github.com/codesenberg/bombardier/releases/download/v1.2.4/bombardier-linux-amd64
  - name: ctop
    enable: "1"
    version_arg: -v
    version: "0.7.3"
    download_url: https://github.com/bcicen/ctop/releases/download/v0.7.3/ctop-0.7.3-linux-amd64
  - name: docker-compose
    enable: "{{ is_wsl1 }}"
    version_arg: "--version"
    version: "1.29.2"
    download_url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
  - name: kubectl
    enable: "1"
    version_arg: "version --client --short"
    version: "1.20.4"
    download_url: https://storage.googleapis.com/kubernetes-release/release/v1.20.4/bin/linux/amd64/kubectl
  - name: sops
    enable: "1"
    version_arg: "--version"
    version: "3.7.1"
    download_url: https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
  - name: stern
    enable: "1"
    version_arg: "--version"
    version: "1.11.0"
    download_url: https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64

targz_binary_install:
  - name: cert
    enable: "1"
    version_arg: "-v"
    version: "0.15.0"
    download_url: https://github.com/genkiroid/cert/releases/download/0.15.0/cert_0.15.0_linux_64bit.tar.gz
    copy_root: ""
    binaries:
      - cert
  - name: eksctl
    enable: "1"
    version_arg: "version"
    version: "0.55.0"
    download_url: https://github.com/weaveworks/eksctl/releases/download/0.55.0/eksctl_Linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - eksctl
  - name: grpcurl
    enable: "1"
    version_arg: "--version"
    version: "1.7.0"
    download_url: https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz
    copy_root: ""
    binaries:
      - grpcurl
  - name: helm
    enable: "1"
    version_arg: "version --short"
    version: "3.5.4"
    download_url: https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz
    copy_root: linux-amd64/
    binaries:
      - helm
  - name: kubeval
    enable: "1"
    version_arg: "--version"
    version: "0.16.1"
    download_url: https://github.com/instrumenta/kubeval/releases/download/v0.16.1/kubeval-linux-amd64.tar.gz
    copy_root: ""
    binaries:
      - kubeval
  - name: tldr
    enable: "1"
    version_arg: "--version"
    version: "0.6.1"
    download_url: https://github.com/isacikgoz/tldr/releases/download/v0.6.1/tldr_0.6.1_linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - tldr
