apt_tools:
  - apache2-utils
  - direnv
  - git-lfs
  - jq
  - moreutils
  - peco
  - pkg-config
  - python3-pip
  - sshpass
  - tree
  - unzip
bombardier:
  - version: "1.2.4"
ctop:
  - version: "0.7.3"
grpcurl:
  - version: "1.7.0"
cert:
  - version: "0.15.0"
