feature_enabed:
  apts: "true"
  aqua: "true"
  azcli: "true"
  binary: "true"
  binary_archive: "true"
  dotnet: "true"
  dpkg: "true"
  git: "true"
  git_tools: "true"
  go: "true"
  krew: "true"
  pip3: "true"
  terraform: "true"

apts:
  - apache2-utils
  - fd-find
  - git-lfs
  - graphviz # require for terraform graph and ansible-playbook-graph
  - htop
  - hub
  - jq
  - moreutils
  - pkg-config
  - python3-pip
  - sshpass
  - tree
  - unzip
  - yamllint
  - whois

aqua:
  global_path: "{{ ansible_home }}/.config/aquaproj-aqua/aqua.yaml" # placed via dotfiles

binary:
  - name: linkerd # `linkerd version --client` https://github.com/linkerd/linkerd2
    version_arg: "version --client"
    version: "2.14.10"
    download_url: https://github.com/linkerd/linkerd2/releases/download/stable-2.14.10/linkerd2-cli-stable-2.14.10-linux-amd64

binary_archive:
  - name: aqua # `aqua --version` https://github.com/aquaproj/aqua
    version_arg: "--version"
    version: "2.37.2"
    download_url: https://github.com/aquaproj/aqua/releases/download/v2.37.2/aqua_linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - aqua
  - name: cert # https://github.com/genkiroid/cert
    version_arg: "-v"
    version: "1.0.0"
    download_url: https://github.com/genkiroid/cert/releases/download/1.0.0/cert_1.0.0_linux_64bit.tar.gz
    copy_root: ""
    binaries:
      - cert
  - name: tldr # https://github.com/isacikgoz/tldr
    version_arg: "--version"
    version: "0.6.1"
    download_url: https://github.com/isacikgoz/tldr/releases/download/v0.6.1/tldr_0.6.1_linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - tldr

dotnet:
  - version: "8.0"
  - version: "9.0"

dpkg:
  - name: session-manager-plugin # https://github.com/aws/session-manager-plugin
    version_arg: "--version"
    version: "1.2.650.0"
    download_url: https://s3.amazonaws.com/session-manager-downloads/plugin/1.2.650.0/ubuntu_64bit/session-manager-plugin.deb

git_tools:
  - name: kube-ps1
    git_https_url: https://github.com/jonmosco/kube-ps1.git
  - name: kubectx
    git_https_url: https://github.com/ahmetb/kubectx.git
    link_binaries:
      - kubectx
      - kubens

go:
  version: "go" # install latest

krew: # https://github.com/kubernetes-sigs/krew
  version: "0.4.4"

krew_plugins:
  - name: explore # https://github.com/keisku/kubectl-explore A better kubectl explain with the fuzzy finder
    install_check_arg: "--help"
  - name: fuzzy # https://github.com/d-kuro/kubectl-fuzzy Instead of specifying full resource names to kubectl commands, you can choose them from an interactive list that you can filter by typing a few characters.
    install_check_arg: "--help"
  - name: get-all # https://github.com/corneliusweig/ketall Like `kubectl get all`, but get really all resources
    install_check_arg: "--help"
  - name: iexec # https://github.com/gabeduke/kubectl-iexec Kubectl plugin to interactively exec into a pod
    install_check_arg: "--help"
  - name: images # https://github.com/chenjiandongx/kubectl-images Show container images used in the cluster.
    install_check_arg: "--help"
  - name: lineage # https://github.com/tohjustin/kube-lineage display all dependencies or dependents of an object in a Kubernetes cluster
    install_check_arg: "--help"
  - name: ktop # https://github.com/vladimirvivien/ktop A top-like tool for your Kubernetes clusters
    install_check_arg: "--help"
  - name: neat # https://github.com/itaysk/kubectl-neat Clean up Kubernetes yaml and json output to make it readable
    install_check_arg: "--help"
  - name: resource-capacity # https://github.com/robscott/kube-capacity A simple CLI that provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster
    install_check_arg: "--help"
  - name: rolesum # https://github.com/Ladicle/kubectl-rolesum Summarize Kubernetes RBAC roles for the specified subjects.
    install_check_arg: "--help"
  - name: view-secret # https://github.com/elsesiy/kubectl-view-secret Kubernetes CLI plugin to decode Kubernetes secrets
    install_check_arg: "--help"
  - name: who-can # https://github.com/aquasecurity/kubectl-who-can Show who has RBAC permissions to perform actions on different resources in Kubernetes
    install_check_arg: "--help"

pip3:
  - name: ansible-lint # https://github.com/ansible/ansible-lint
    version: "24.9.2"
  - name: ansible-playbook-grapher # require: graphviz https://github.com/haidaraM/ansible-playbook-grapher
    version: "2.3.0"
