apt_tools:
  - apache2-utils
  - direnv
  - git-lfs
  - jq
  - moreutils
  - peco
  - pkg-config
  - python3-pip
  - sshpass
  - tree
  - unzip
grpcurl:
  - version: "1.7.0"
cert:
  - version: "0.15.0"
tldr:
  - version: "0.6.1"

binary_install:
  - name: argocd
    enable: "1"
    version_arg: "version"
    version: "1.8.7"
    download_url: https://github.com/argoproj/argo-cd/releases/download/v1.8.7/argocd-linux-amd64
  - name: bombardier
    enable: "1"
    version_arg: "--version"
    version: "1.2.4"
    download_url: https://github.com/codesenberg/bombardier/releases/download/v1.2.4/bombardier-linux-amd64
  - name: ctop
    enable: "1"
    version_arg: -v
    version: "0.7.3"
    download_url: https://github.com/bcicen/ctop/releases/download/v0.7.3/ctop-0.7.3-linux-amd64
  - name: docker-compose
    enable: "{{ is_wsl1 }}"
    version_arg: "--version"
    version: "1.29.2"
    download_url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
  - name: kubectl
    enable: "1"
    version_arg: "version --client --short"
    version: "1.20.4"
    download_url: https://storage.googleapis.com/kubernetes-release/release/v1.20.4/bin/linux/amd64/kubectl
  - name: sops
    enable: "1"
    version_arg: "--version"
    version: "3.7.1"
    download_url: https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
