apt_tools:
  - apache2-utils
  - direnv
  - git-lfs
  - htop
  - hub
  - jq
  - moreutils
  - peco
  - pkg-config
  - python3-pip
  - sshpass
  - tree
  - unzip
  - whois

binary_install:
  - name: argocd
    version_arg: "version --client"
    version: "2.1.5"
    download_url: https://github.com/argoproj/argo-cd/releases/download/v2.1.5/argocd-linux-amd64
  - name: bombardier
    version_arg: "--version"
    version: "1.2.4"
    download_url: https://github.com/codesenberg/bombardier/releases/download/v1.2.4/bombardier-linux-amd64
  - name: ctop
    version_arg: "-v"
    version: "0.7.3"
    download_url: https://github.com/bcicen/ctop/releases/download/v0.7.3/ctop-0.7.3-linux-amd64
  - name: grpc_health_probe
    checksum_type: sha256sum
    checksum: 68c7301c41b1bd1d89668bf27d5314a10b8330f694e711401fe1494d2c9780c2
    download_url: https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.6/grpc_health_probe-linux-amd64
  - name: linkerd
    version_arg: "version --client"
    version: "2.10.2"
    download_url: https://github.com/linkerd/linkerd2/releases/download/stable-2.10.2/linkerd2-cli-stable-2.10.2-linux-amd64
  - name: kubectl
    version_arg: "version --client --short"
    version: "1.22.6"
    download_url: https://storage.googleapis.com/kubernetes-release/release/v1.22.6/bin/linux/amd64/kubectl
  - name: sops
    version_arg: "--version"
    version: "3.7.3"
    download_url: https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux
  - name: stern
    version_arg: "--version"
    version: "1.11.0"
    download_url: https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64

targz_binary_install:
  - name: cert
    version_arg: "-v"
    version: "0.15.0"
    download_url: https://github.com/genkiroid/cert/releases/download/0.15.0/cert_0.15.0_linux_64bit.tar.gz
    copy_root: ""
    binaries:
      - cert
  - name: conftest
    version_arg: "-v"
    version: "0.27.0"
    download_url: https://github.com/open-policy-agent/conftest/releases/download/v0.27.0/conftest_0.27.0_Linux_x86_64.tar.gz
    copy_root: ""
    binaries:
      - conftest
  - name: eksctl
    version_arg: "version"
    version: "0.55.0"
    download_url: https://github.com/weaveworks/eksctl/releases/download/0.55.0/eksctl_Linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - eksctl
  - name: grpcurl
    version_arg: "--version"
    version: "1.7.0"
    download_url: https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz
    copy_root: ""
    binaries:
      - grpcurl
  - name: helm
    version_arg: "version --short"
    version: "3.5.4"
    download_url: https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz
    copy_root: linux-amd64/
    binaries:
      - helm
  - name: kubeval
    version_arg: "--version"
    version: "0.16.1"
    download_url: https://github.com/instrumenta/kubeval/releases/download/v0.16.1/kubeval-linux-amd64.tar.gz
    copy_root: ""
    binaries:
      - kubeval
  - name: lazygit
    version_arg: "--version"
    version: "0.34"
    download_url: https://github.com/jesseduffield/lazygit/releases/download/v0.34/lazygit_0.34_Linux_x86_64.tar.gz
    copy_root: ""
    binaries:
      - lazygit
  - name: step
    version_arg: "--version"
    version: "0.17.6"
    download_url: https://dl.step.sm/gh-release/cli/gh-release-header/v0.17.6/step_linux_0.17.6_amd64.tar.gz
    copy_root: "step_0.17.6/bin/"
    binaries:
      - step
    dest_override: /usr/bin/
  - name: tldr
    version_arg: "--version"
    version: "0.6.1"
    download_url: https://github.com/isacikgoz/tldr/releases/download/v0.6.1/tldr_0.6.1_linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - tldr
  - name: yq
    version_arg: "--version"
    version: "4.25.2"
    download_url: https://github.com/mikefarah/yq/releases/download/v4.25.2/yq_linux_amd64.tar.gz
    copy_root: ""
    binaries:
      - yq_linux_amd64
    dest_override: /usr/local/bin/yq # rename to yq

git_tools:
  - name: kubectx
    git_https_url: https://github.com/ahmetb/kubectx.git
    link_binaries:
      - kubectx
      - kubens
  - name: kube-ps1
    git_https_url: https://github.com/jonmosco/kube-ps1.git

homebrew:
  - packages:
      - { name: "hello", state: "present" }

anyenv:
  - goenv: "false"
    nodenv: "true"
    pyenv: "false"

aws_cli:
  - version: "2.1.35"

dotnet:
  - version: "6.0"

gh_cli:
  - version: "2.10.1"

krew:
  - version: "0.4.3"

kubectl_plugin:
  - name: explore
    install_check_arg: "--help"
  - name: fuzzy
    install_check_arg: "--help"
  - name: get-all
    install_check_arg: "--help"
  - name: iexec
    install_check_arg: "--help"
  - name: images
    install_check_arg: "--help"
  - name: neat
    install_check_arg: "--help"
  - name: resource-capacity
    install_check_arg: "--help"
  - name: rolesum
    install_check_arg: "--help"
  - name: view-secret
    install_check_arg: "--help"
  - name: who-can
    install_check_arg: "--help"

terraform:
  - version: "1.1.6"
