# helm
- name: "Install helm"
  include: include_role/install_helm.yaml
  with_items: "{{ helm }}"
  loop_control:
    loop_var: args

# kubectx
- name: "Install kubectx"
  include: include_role/install_kubectx.yaml

# kube-ps1
- name: "kube-ps1 - clone"
  become: yes
  git:
    repo: https://github.com/jonmosco/kube-ps1.git
    dest: "{{ ansible_home}}/github/kube-ps1"
    accept_hostkey: yes

# stern
- name: "Install stern"
  include: include_role/install_stern.yaml
  with_items: "{{ stern }}"
  loop_control:
    loop_var: args

# kubeval
- name: "Install kubeval"
  include: include_role/install_kubeval.yaml
  with_items: "{{ kubeval }}"
  loop_control:
    loop_var: args
