---
# kubectl
- name: pickup installed kubectl versions
  shell: kubectl version | grep {{ kubectl_version }}
  register: kubectl_exists
  changed_when: false
  ignore_errors: yes

- name: download kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: "{{ ansible_home }}/kubectl"
  register: download_kubectl
  when: kubectl_exists is failed

- name: copy kubectl
  become: yes
  copy:
    src: "{{ ansible_home }}/kubectl"
    dest: /usr/local/bin
  when: kubectl_exists is failed

- name: remove kubectl
  file:
    state: absent
    path: "{{ ansible_home }}/kubectl"
  when: download_kubectl is succeeded

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/kubectl
    mode: "0755"

- name: confirm kubectl exists
  shell: ls /usr/local/bin/kubectl && kubectl version | grep {{ kubectl_version }}
  changed_when: false

# kubeadm
- name: add kubeadm apt_key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add kube apt
  become: yes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: install kubeadm
  become: yes
  apt:
    pkg: kubeadm
    update_cache: yes

# helm
- name: pickup installed helm versions
  shell: helm version | grep {{ helm_version }}
  register: helm_exists
  changed_when: false
  ignore_errors: yes

- name: download helm
  get_url:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
    dest: "{{ ansible_home }}/helm.tar.gz"
  register: download_helm
  when: helm_exists is failed

- name: unarchive helm
  command: tar -zxvf "{{ ansible_home }}/helm.tar.gz"
  args:
    chdir: "{{ ansible_home }}/"
  register: unarchive_helm
  when: helm_exists is failed

- name: copy helm
  become: yes
  copy:
    src: "{{ ansible_home }}/linux-amd64/helm"
    dest: /usr/local/bin
  when: helm_exists is failed

- name: copy tiller
  become: yes
  copy:
    src: "{{ ansible_home }}/linux-amd64/tiller"
    dest: /usr/local/bin
  when: helm_exists is failed

- name: remove helm.tar.gz
  file:
    state: absent
    path: "{{ ansible_home }}/helm.tar.gz"
  when: download_helm is succeeded

- name: remove helm.tar.gz
  file:
    state: absent
    path: "{{ ansible_home }}/helm"
  when: unarchive_helm is succeeded

- name: remove helm dir
  file:
    state: absent
    path: "{{ ansible_home }}/linux-amd64"
  when: unarchive_helm is succeeded

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/helm
    mode: "0755"

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/tiller
    mode: "0755"

- name: confirm helm exists
  shell: ls /usr/local/bin/helm && helm version | grep {{ helm_version }}
  changed_when: false

# kubectx
- name: clone kubectx
  become: yes
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: "{{ ansible_home}}/github/kubectx"
    accept_hostkey: yes

- name: create kubectx symlinks
  become: yes
  file:
    src: "{{ ansible_home }}/github/kubectx/kubectx"
    dest: "/usr/local/bin/kubectx"
    state: link

- name: create kubens symlinks
  become: yes
  file:
    src: "{{ ansible_home }}/github/kubectx/kubens"
    dest: "/usr/local/bin/kubens"
    state: link

# stern
- name: pickup installed stern versions
  shell: stern --version | grep {{ stern_version }}
  register: stern_exists
  changed_when: false
  ignore_errors: yes

- name: download stern
  get_url:
    url: https://github.com/wercker/stern/releases/download/{{ stern_version }}/stern_linux_amd64
    dest: "{{ ansible_home }}/stern"
  register: download_stern
  when: stern_exists is failed

- name: copy stern
  become: yes
  copy:
    src: "{{ ansible_home }}/stern"
    dest: /usr/local/bin
  when: stern_exists is failed

- name: remove stern
  file:
    state: absent
    path: "{{ ansible_home }}/stern"
  when: download_stern is succeeded

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/stern
    mode: "0755"

- name: confirm stern exists
  shell: ls /usr/local/bin/stern && stern --version | grep {{ stern_version }}
  changed_when: false

# kubergrunt
- name: pickup installed kubergrunt versions
  shell: kubergrunt --version | grep {{ kubergrunt_version }}
  register: kubergrunt_exists
  changed_when: false
  ignore_errors: yes

- name: download kubergrunt
  get_url:
    url: https://github.com/gruntwork-io/kubergrunt/releases/download/v{{ kubergrunt_version }}/kubergrunt_linux_amd64
    dest: "{{ ansible_home }}/kubergrunt"
  register: download_kubergrunt
  when: kubergrunt_exists is failed

- name: copy kubergrunt
  become: yes
  copy:
    src: "{{ ansible_home }}/kubergrunt"
    dest: /usr/local/bin
  when: kubergrunt_exists is failed

- name: remove kubergrunt
  file:
    state: absent
    path: "{{ ansible_home }}/kubergrunt"
  when: download_kubergrunt is succeeded

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/kubergrunt
    mode: "0755"

- name: confirm kubergrunt exists
  shell: ls /usr/local/bin/kubergrunt && kubergrunt --version | grep {{ kubergrunt_version }}
  changed_when: false

# istioctl
- name: pickup installed istioctl versions
  shell: istioctl version | grep {{ istioctl_version }}
  register: istioctl_exists
  changed_when: false
  ignore_errors: yes

- name: download istioctl
  get_url:
    url: https://git.io/getLatestIstio
    dest: "{{ ansible_home }}/istio_install.sh"
  register: download_istioctl
  when: istioctl_exists is failed

- name: install istioctl sh
  shell: ISTIO_VERSION={{ istioctl_version }} . ./istio_install.sh
  args:
    chdir: "{{ ansible_home }}/"
  when: download_istioctl is succeeded
  changed_when: false

- name: copy istioctl
  become: yes
  copy:
    src: "{{ ansible_home }}/istio-{{ istioctl_version }}/bin/istioctl"
    dest: /usr/local/bin
  when: istioctl_exists is failed

- name: remove istioctl
  file:
    state: absent
    path: "{{ ansible_home }}/istio-{{ istioctl_version }}/bin/"
  when: download_istioctl is succeeded

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/istioctl
    mode: "0755"

- name: confirm istioctl exists
  shell: ls /usr/local/bin/istioctl && istioctl version | grep {{ istioctl_version }}
  changed_when: false
