---
# .kube/config
- name: check user exists
  stat:
    path: "/mnt/c/Users/guitarrapc/.kube/config"
  register: win_user_stat_result

- name: create ~/kube directory
  file:
    path: "{{ ansible_home }}/.kube"
    state: directory
    mode: "0755"

- name: create ~/kube/.config symlinks
  file:
    src: "/mnt/c/Users/guitarrapc/.kube/config"
    dest: "{{ ansible_home }}/.kube/config"
    state: link
  when: win_user_stat_result.stat.exists

# kubectl
- name: check kubectl installed
  shell: kubectl version --client --short | grep {{ kubectl_version }}
  register: kubectl_exists
  changed_when: false
  ignore_errors: yes

- name: remove docker for windows kubectl if exists.
  become: yes
  file:
    path: /usr/local/bin/kubectl
    state: absent
  when: kubectl_exists is failed

- name: download kubectl
  become: yes
  shell: curl -Ls "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
  register: download_kubectl
  when: kubectl_exists is failed

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/kubectl
    mode: "0755"
  when: kubectl_exists is failed

# kubeadm
# - name: add kubeadm apt key
#   become: yes
#   apt_key:
#     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add kubeadm apt key
  become: yes
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

- name: add kube apt
  become: yes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: install kubeadm
  become: yes
  apt:
    pkg: kubeadm
    update_cache: yes

# helm3
- name: check helm3 installed
  shell: helm version --short | grep {{ helm_version }}
  register: helm3_exists
  changed_when: false
  ignore_errors: yes

- name: download helm3
  get_url:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
    dest: "{{ ansible_home }}/helm3.tar.gz"
  register: download_helm3
  when: helm3_exists is failed

- name: unarchive helm3
  command: tar -zxvf "{{ ansible_home }}/helm3.tar.gz"
  args:
    chdir: "{{ ansible_home }}/"
  register: unarchive_helm3
  when: helm3_exists is failed

- name: copy helm3
  become: yes
  copy:
    src: "{{ ansible_home }}/linux-amd64/helm"
    dest: /usr/local/bin
  when: helm3_exists is failed

- name: remove helm3.tar.gz
  file:
    state: absent
    path: "{{ ansible_home }}/helm3.tar.gz"
  when: download_helm3 is succeeded

- name: remove helm3 dir
  file:
    state: absent
    path: "{{ ansible_home }}/linux-amd64"
  when: unarchive_helm3 is succeeded

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/helm
    mode: "0755"

# kubectx
- name: clone kubectx
  become: yes
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: "{{ ansible_home}}/github/kubectx"
    accept_hostkey: yes

- name: create kubectx symlinks
  become: yes
  file:
    src: "{{ ansible_home }}/github/kubectx/kubectx"
    dest: "/usr/local/bin/kubectx"
    state: link

- name: create kubens symlinks
  become: yes
  file:
    src: "{{ ansible_home }}/github/kubectx/kubens"
    dest: "/usr/local/bin/kubens"
    state: link

# stern
- name: check stern installed
  shell: stern --version | grep {{ stern_version }}
  register: stern_exists
  changed_when: false
  ignore_errors: yes

- name: download stern
  become: yes
  get_url:
    url: https://github.com/wercker/stern/releases/download/{{ stern_version }}/stern_linux_amd64
    dest: "/usr/local/bin/stern"
  register: download_stern
  when: stern_exists is failed

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/stern
    mode: "0755"

# kubergrunt
- name: check kubergrunt installed
  shell: kubergrunt --version | grep {{ kubergrunt_version }}
  register: kubergrunt_exists
  changed_when: false
  ignore_errors: yes

- name: download kubergrunt
  become: yes
  get_url:
    url: https://github.com/gruntwork-io/kubergrunt/releases/download/v{{ kubergrunt_version }}/kubergrunt_linux_amd64
    dest: "/usr/local/bin/kubergrunt"
  register: download_kubergrunt
  when: kubergrunt_exists is failed

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/kubergrunt
    mode: "0755"

# istioctl
- name: check istioctl installed
  shell: istioctl version | grep {{ istioctl_version }}
  register: istioctl_exists
  changed_when: false
  ignore_errors: yes

- name: download istioctl
  get_url:
    url: https://git.io/getLatestIstio
    dest: "{{ ansible_home }}/istio_install.sh"
  register: download_istioctl
  when: istioctl_exists is failed

- name: install istioctl sh
  shell: ISTIO_VERSION={{ istioctl_version }} . ./istio_install.sh
  args:
    chdir: "{{ ansible_home }}/"
  when:
    - istioctl_exists is failed
    - download_istioctl is succeeded
  changed_when: false

- name: copy istioctl
  become: yes
  copy:
    src: "{{ ansible_home }}/istio-{{ istioctl_version }}/bin/istioctl"
    dest: /usr/local/bin
  when:
    - istioctl_exists is failed
    - download_istioctl is succeeded

- name: remove istioctl from bin/
  file:
    state: absent
    path: "{{ ansible_home }}/istio-{{ istioctl_version }}/bin/"
  when:
    - istioctl_exists is failed
    - download_istioctl is succeeded

- name: remove istioctl sh
  file:
    state: absent
    path: "{{ ansible_home }}/istio_install.sh"
  when:
    - istioctl_exists is failed
    - download_istioctl is succeeded

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/istioctl
    mode: "0755"
  when:
    - istioctl_exists is failed
    - download_istioctl is succeeded

# kubesec
- name: check kubesec installed
  shell: kubesec --version | grep {{ kubesec_version }}
  register: kubesec_exists
  changed_when: false
  ignore_errors: yes

- name: download kubesec
  become: yes
  get_url:
    url: https://github.com/shyiko/kubesec/releases/download/{{ kubesec_version }}/kubesec-{{ kubesec_version }}-linux-amd64
    dest: "/usr/local/bin/kubesec"
  register: download_kubesec
  when: kubesec_exists is failed

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/kubesec
    mode: "a+x"
  when: download_kubesec is succeeded

# kubeval
- name: check kubeval installed
  shell: kubeval --version | grep {{ kubeval_version }}
  register: kubeval_exists
  changed_when: false
  ignore_errors: yes

- name: download kubeval
  get_url:
    url: https://github.com/instrumenta/kubeval/releases/download/{{ kubeval_version }}/kubeval-linux-amd64.tar.gz
    dest: "{{ ansible_home }}/kubeval.tar.gz"
  register: download_kubeval
  when: kubeval_exists is failed

- name: unarchive kubeval
  command: tar -zxvf "{{ ansible_home }}/kubeval.tar.gz"
  args:
    chdir: "{{ ansible_home }}/"
  register: unarchive_kubeval
  when: kubeval_exists is failed

- name: copy kubeval
  become: yes
  copy:
    src: "{{ ansible_home }}/kubeval"
    dest: /usr/local/bin/kubeval
  when: kubeval_exists is failed

- name: remove kubeval files
  file:
    state: absent
    path: "{{ ansible_home }}/{{ item }}"
  with_items:
    - kubeval.tar.gz
    - LICENSE
    - README.md
    - kubeval
  when: kubeval_exists is failed

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/kubeval
    mode: "0755"
  when: kubeval_exists is failed

# mozilla/sops
- name: check sops installed
  shell: sops --version | grep {{ sops_version }}
  register: sops_exists
  changed_when: false
  ignore_errors: yes

- name: download sops
  become: yes
  get_url:
    url: https://github.com/mozilla/sops/releases/download/v{{ sops_version }}/sops-v{{ sops_version }}.linux
    dest: "/usr/local/bin/sops"
  register: download_sops
  when: sops_exists is failed

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/sops
    mode: "0755"
  when: sops_exists is failed

# argocd
- name: check argocd installed
  shell: argocd version | grep {{ argocd_version }}
  register: argocd_exists
  changed_when: false
  ignore_errors: yes

- name: download argocd
  become: yes
  get_url:
    url: https://github.com/argoproj/argo-cd/releases/download/v{{ argocd_version }}/argocd-linux-amd64
    dest: "/usr/local/bin/argocd"
  register: download_argocd
  when: argocd_exists is failed

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/argocd
    mode: "0755"
  when: argocd_exists is failed
