# kubectx
- name: "Install kubectx"
  include: include_role/install_kubectx.yaml

# kube-ps1
- name: "kube-ps1 - clone"
  become: yes
  git:
    repo: https://github.com/jonmosco/kube-ps1.git
    dest: "{{ ansible_home}}/github/kube-ps1"
    accept_hostkey: yes

