---
- name: check ruby installed
  ansible.builtin.shell: set -o pipefail && rbenv versions | grep {{ ruby_version }}
  register: rbenv_version
  changed_when: false
  ignore_errors: true

- name: install ruby {{ ruby_version }}
  ansible.builtin.command: rbenv install {{ ruby_version }}
  when: rbenv_version is failed

- name: install ruby bundler
  gem:
    name: bundler
  when: rbenv_version is success
