---

- name: pickup installed ruby versions
  shell: rbenv versions | grep {{ ruby_version }}
  register: rbenv_version
  changed_when: false
  ignore_errors: yes

- name: install ruby
  shell: rbenv install {{ ruby_version }}
  when: rbenv_version is failed

- name: install bundler
  gem:
    name: bundler