# https://github.com/lukesampson/scoop/tree/master/bucket
- name: "Install linux tools"
  scoop_install:
    state: present
    bucket: main
    name:
      - gow
      - jq
      - sudo
      - time
      - unzip
      - openssl
      - apache
      - netcat

- name: "Install windows tools"
  scoop_install:
    state: present
    bucket: main
    name:
      - 7zip
      - aws
      - chromedriver
      - git
      - git-lfs
      - ngrok
      - pwsh
      - terraform
      - gibo
      - helm
      - mysql-workbench

- name: "Install Programming Languages"
  scoop_install:
    state: present
    bucket: main
    name:
      - go
      - nvm
      - yarn
