# https://github.com/lukesampson/scoop/tree/master/bucket
- name: "Install fundamentals"
  scoop_install:
    state: present
    bucket: main
    name:
      - git
      - 7zip
      - sudo

- name: "Install linux tools"
  scoop_install:
    state: present
    bucket: main
    name:
      - busybox
      - figlet
      - jq
      - openssl
      - sops
      - time
      - unzip
      - vim

- name: "Install windows tools"
  scoop_install:
    state: present
    bucket: main
    name:
      - aws
      - azure-cli
      - bazel
      - chromedriver
      - dive
      - hub
      - gibo
      - git-lfs
      - helm
      - kubeval
      - mysql-workbench
      - ngrok
      - nvm
      - shellcheck
      - pwsh
      - terraform
      - tflint
      - yarn

- name: "Install Programming Languages"
  scoop_install:
    state: present
    bucket: main
    name:
      - python
