# https://github.com/lukesampson/scoop/tree/master/bucket
# sudo is not required from Windows 11 24H2, as it is offer by default from Developer settings.
- name: "Install fundamentals"
  scoop_install:
    state: present
    bucket: main
    name:
      - 7zip

- name: "Install linux tools"
  scoop_install:
    state: present
    bucket: main
    name:
      - busybox
      - duf
      - fd
      - figlet
      - jq
      - openssl
      - sops
      - tenv
      - tflint
      - time
      - unzip
      - vim
      - yq

- name: "Install windows tools"
  scoop_install:
    state: present
    bucket: main
    name:
      - actionlint
      - aws
      - aws-vault
      - azure-cli
      - chromedriver
      - dive
      - gh
      - hugo
      - hugo-extended
      - gibo
      - helm
      - kubens
      - kubectx
      - nvm
      - shellcheck
      - pwsh

- name: "Install Programming Languages"
  scoop_install:
    state: present
    bucket: main
    name:
      - python

- name: "UnInstall tools"
  scoop_install:
    state: absent
    bucket: main
    name:
      - bazel # dont't use currently
      - terraform # use tenv instead
      - mysql-workbench # dont't use currently
      - ngrok
