# https://github.com/lukesampson/scoop/tree/master/bucket
- name: "Install fundamentals"
  scoop_install:
    state: present
    bucket: main
    name:
      - git
      - 7zip
      - sudo

- name: "Install linux tools"
  scoop_install:
    state: present
    bucket: main
    name:
      - busybox
      - jq
      - netcat
      - openssl
      - sops
      - time
      - unzip

- name: "Install windows tools"
  scoop_install:
    state: present
    bucket: main
    name:
      - aws
      - bazel
      - chromedriver
      - dive
      - gibo
      - git-lfs
      - helm
      - kubeval
      - mysql-workbench
      - ngrok
      - pwsh
      - terraform

- name: "Install Programming Languages"
  scoop_install:
    state: present
    bucket: main
    name:
      - go
      - nvm
      - python
      - yarn
