---
# credential mapping with host
# aws
- name: "{{ ansible_role_name}}: aws - check src .aws/credentials exists"
  stat:
    path: "{{ win_aws_config_path }}/credentials"
  register: win_aws_credentials_stat_result

- name: "{{ ansible_role_name}}: aws - check src .aws/config exists"
  stat:
    path: "{{ win_aws_config_path }}/config"
  register: win_aws_config_stat_result

- name: "{{ ansible_role_name}}: aws - check .aws/credentials is link"
  stat:
    path: "{{ ansible_home }}/.aws/credentials"
  register: aws_credentials_link

- name: "{{ ansible_role_name}}: aws - check .aws/config is link"
  stat:
    path: "{{ ansible_home }}/.aws/config"
  register: aws_config_link

- name: "{{ ansible_role_name}}: aws -Create .aws directory"
  file:
    path: "{{ ansible_home }}/.aws"
    state: directory

- name: "{{ ansible_role_name}}: aws - delete ~/.aws/credentials default file"
  file:
    path: "{{ ansible_home }}/.aws/credentials"
    state: absent
  when: (win_aws_credentials_stat_result.stat.exists) and (aws_credentials_link.stat.exists) and (not aws_credentials_link.stat.islnk)

- name: "{{ ansible_role_name}}: aws - delete ~/.aws/config default file"
  file:
    path: "{{ ansible_home }}/.aws/config"
    state: absent
  when: (win_aws_config_stat_result.stat.exists) and (aws_config_link.stat.exists) and (not aws_config_link.stat.islnk)

- name: "{{ ansible_role_name}}: aws - create ~/.aws/credentials symlinks"
  file:
    src: "{{win_aws_config_path}}/credentials"
    dest: "{{ ansible_home }}/.aws/credentials"
    state: link
  when: win_aws_credentials_stat_result.stat.exists

- name: "{{ ansible_role_name}}: aws - create ~/.aws/config symlinks"
  file:
    src: "{{win_aws_config_path}}/config"
    dest: "{{ ansible_home }}/.aws/config"
    state: link
  when: win_aws_config_stat_result.stat.exists

# .kube/config
- name: "{{ ansible_role_name}}: kubectl - check src .kub/config exists"
  stat:
    path: "{{ win_kube_config_path }}"
  register: win_kube_config_stat_result

- name: "{{ ansible_role_name}}: kubectl - check .kube/config is link"
  stat:
    path: "{{ ansible_home }}/.kube/config"
  register: kube_config_link

- name: "{{ ansible_role_name}}: kubectl - create ~/.kube directory"
  file:
    path: "{{ ansible_home }}/.kube"
    state: directory
    mode: "0755"

- name: "{{ ansible_role_name}}: kubectl - delete ~/.kube/config default file"
  file:
    path: "{{ ansible_home }}/.kube"
    state: absent
  when: (win_kube_config_stat_result.stat.exists) and (kube_config_link.stat.exists) and (not kube_config_link.stat.islnk)

- name: "{{ ansible_role_name}}: kubectl - create ~/.kube/config symlinks"
  file:
    src: "{{ win_kube_config_path }}"
    dest: "{{ ansible_home }}/.kube/config"
    state: link
  when: win_kube_config_stat_result.stat.exists
