- name: "link .aws credential"
  include: include_role/credentials_aws.yaml
  with_items: "{{ win_aws_config }}"
  loop_control:
    loop_var: args

- name: "link .kube credential"
  include: include_role/credentials_kube.yaml
  with_items: "{{ win_kube_config }}"
  loop_control:
    loop_var: args

