---
- name: Create github directory
  file:
    path: "{{ base_path }}"
    state: directory

- name: Clone & Fetch dotfiles
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items: "{{ repository }}"
  when: repository is defined

# must use shell, instead of command.
# ref: https://stackoverflow.com/questions/56989048/issue-in-ansible-playbook-command/56991314
- name: Create symlinks
  become: yes
  become_user: "{{ lookup('env','USER') }}"
  shell: bash -lc "{{ run_dotfiles }}"
  changed_when: False
  register: dotfiles

- debug: msg="{{ dotfiles.stdout_lines }}"
