- name: "apt - Install tools"
  become: true
  ansible.builtin.apt:
    pkg: "{{ apt_tools }}"
    update_cache: true

- name: pip3 - Install pip3 packages
  ansible.builtin.pip:
    name: "{{ pip_tools }}"

- name: "git - Install git cli"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_git.yaml

- name: "binary - Install tools"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_binary.yaml
  with_items: "{{ binary_install }}"
  loop_control:
    loop_var: args

- name: ".tar.gz - Install tools"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_binary_targz.yaml
  with_items: "{{ targz_binary_install }}"
  loop_control:
    loop_var: args

- name: "git clone - Install git tools"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_git_tool.yaml
  with_items: "{{ git_tools }}"
  loop_control:
    loop_var: args

- name: "dpkg - Install tools"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_dpkg.yaml
  with_items: "{{ dpkg_install }}"
  loop_control:
    loop_var: args

# # # too slow.... may be remove in future. packages should not depends on brew.
# # - name: "Install homebrew"
# #   ansible.builtin.include_tasks: ../include_role/ubuntu/install_homebrew.yaml
# #   with_items: "{{ homebrew }}"
# #   loop_control:
# #     loop_var: args

# each packages
- name: "asdf - Install asdf"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_asdf.yaml
  with_items: "{{ asdf }}"
  loop_control:
    loop_var: args

- name: "asdf - Install asdf plugins"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_asdf_plugins.yaml
  with_items: "{{ asdf_plugins }}"
  loop_control:
    loop_var: args

- name: ".NET - Install dotnet"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_dotnet.yaml
  with_items: "{{ dotnet }}"
  loop_control:
    loop_var: args
  when: ansible_distribution_version != "22.04"

- name: "krew - Install krew binary"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_krew.yaml
  with_items: "{{ krew }}"
  loop_control:
    loop_var: args

- name: "krew Plugins - Install krew kubectl plugins"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_krew_plugin.yaml
  with_items: "{{ krew_plugins }}"
  loop_control:
    loop_var: args

- name: "terraform - Install terraform"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_terraform.yaml
  with_items: "{{ terraform }}"
  loop_control:
    loop_var: args

- name: "trivy - Install trivy"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_trivy.yaml

# use .devcontainer instead. https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/azcli.md
# too slow download pacakge..... oh my package.microsoft.com ....
- name: "azure - Install azure cli"
  ansible.builtin.include_tasks: ../include_role/ubuntu/install_azurecli.yaml
