---
- name: "apt - install apt tools"
  become: yes
  apt:
    pkg: "{{ apt_tools }}"
    update_cache: yes

- name: "Install binaries"
  include: include_role/install_binary.yaml
  with_items: "{{ binary_install }}"
  loop_control:
    loop_var: args

- name: "Install .tar.gz binaries"
  include: include_role/install_binary_targz.yaml
  with_items: "{{ targz_binary_install }}"
  loop_control:
    loop_var: args

