---
- name: "apt - install apt tools"
  become: yes
  apt:
    pkg: "{{ apt_tools }}"
    update_cache: yes

# tldr
- name: "Install tldr"
  include: include_role/install_tldr.yaml

# bombardier
- name: "Install binaries"
  include: include_role/install_binary.yaml
  with_items: "{{ binary_install }}"
  loop_control:
    loop_var: args

# # bombardier
# - name: "Install bombardier"
#   include: include_role/install_bombardier.yaml
#   with_items: "{{ bombardier }}"
#   loop_control:
#     loop_var: args

# ctop
# - name: "Install ctop"
#   include: include_role/install_ctop.yaml
#   with_items: "{{ ctop }}"
#   loop_control:
#     loop_var: args

# grpcurl
- name: "Install grpcurl"
  include: include_role/install_grpcurl.yaml
  with_items: "{{ grpcurl }}"
  loop_control:
    loop_var: args

# cert
- name: "Install cert"
  include: include_role/install_cert.yaml
  with_items: "{{ cert }}"
  loop_control:
    loop_var: args
