---
- name: "apt - install apt tools"
  become: yes
  apt:
    pkg: "{{ apt_tools }}"
    update_cache: yes

- name: "Install binaries"
  include: ../include_role/ubuntu/install_binary.yaml
  with_items: "{{ binary_install }}"
  loop_control:
    loop_var: args

- name: "Install .tar.gz binaries"
  include: ../include_role/ubuntu/install_binary_targz.yaml
  with_items: "{{ targz_binary_install }}"
  loop_control:
    loop_var: args

- name: "Install git tools"
  include: ../include_role/ubuntu/install_git_tool.yaml
  with_items: "{{ git_tools }}"
  loop_control:
    loop_var: args

- name: "Install homebrew"
  include: ../include_role/ubuntu/install_homebrew.yaml
  with_items: "{{ homebrew }}"
  loop_control:
    loop_var: args

# each packages
- name: "Install aws cli"
  include: ../include_role/ubuntu/install_awscli.yaml
  with_items: "{{ aws_cli }}"
  loop_control:
    loop_var: args

- name: "Install azure cli"
  include: ../include_role/ubuntu/install_azurecli.yaml

- name: "Install dotnet"
  include: ../include_role/ubuntu/install_dotnet.yaml
  with_items: "{{ dotnet }}"
  loop_control:
    loop_var: args

- name: "Install kubectl plugins"
  include: ../include_role/ubuntu/install_kubectl_plugin.yaml
  with_items: "{{ kubectl_plugin }}"
  loop_control:
    loop_var: args

- name: "Install terraform"
  include: ../include_role/ubuntu/install_terraform.yaml
  with_items: "{{ terraform }}"
  loop_control:
    loop_var: args

- name: "Install trivy"
  include: ../include_role/ubuntu/install_trivy.yaml
