homebrew_cask_packages:
  - name: cd-to-terminal
  - name: docker
  - name: dotnet-sdk
  - name: duet
  - name: fork
  - name: goland
  - name: google-chrome
  - name: google-cloud-sdk
  - name: google-japanese-ime
  - name: gitkraken
  - name: kindle
  - name: krisp
  - name: microsoft-teams
  - name: ngrok
  - name: powershell
  - name: rescuetime
  - name: sequel-pro
  - name: slack
  - name: sourcetree
  - name: unity-hub
  - name: visual-studio-code

