# "ansible_home" may be: /home/guitarrapc
- name: "Debug - ansible_home"
  ansible.builtin.debug:
    msg: "{{ ansible_home }}"
- name: "Debug - env.Home"
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'HOME') }}"
- name: "Debug - become env.HOME"
  become: true
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'HOME') }}"

# "ansible_user" may be: guitarrapc
- name: "Debug - ansible_user_id"
  ansible.builtin.debug:
    msg: "{{ ansible_user_id }}"
- name: "Debug - become ansible_user_id"
  become: true
  ansible.builtin.debug:
    msg: "{{ ansible_user_id }}"
- name: "Debug - env.User"
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'USER') }}"
- name: "Debug - become env.User"
  become: true
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'USER') }}"

# "ansible_distribution" may be: "Debian", "SLES", "Ubuntu", "CentOS"
# "ansible_distribution_version" may be: "9.0", "12.2", "18.04", "7.3.1611"
# "ansible_distribution_major_version" may be: "9", "12", 18.04"
# "ansible_distribution_release" may be: "bionic"
# "ansible_os_family" may be: "Debian", "RedHat", "Suse"
# Upper/lower case is important, you can change UPPER or lower via `|uppper` or `|lower`
- name: "Debug - distribution"
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }}"
- name: "Debug - distribution lower case"
  ansible.builtin.debug:
    msg: "{{ ansible_distribution | lower }}"
- name: "Debug - distribution version"
  ansible.builtin.debug:
    msg: "{{ ansible_distribution_version }}"
- name: "Debug - distribution release"
  ansible.builtin.debug:
    msg: "{{ ansible_distribution_release }}"

# Ubuntu on WSL check
- name: "Debug - is_wsl1 or not (Ubuntu only)"
  ansible.builtin.debug:
    msg: "{{ is_wsl1 }}"
  when: ansible_distribution == "Ubuntu"
- name: "Debug - is_wsl2 or not (Ubuntu only)"
  ansible.builtin.debug:
    msg: "{{ is_wsl2 }}"
  when: ansible_distribution == "Ubuntu"
