- name: update brew
  ansible.builtin.command: brew update
  register: result
  ignore_errors: true
  changed_when: result.stdout != 'Already up-to-date.'

- name: "homebrew packages installation"
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ homebrew_packages }}"

- name: "homebrew cask packages installation"
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ homebrew_cask_packages }}"

- name: "homebrew cask fonts installation"
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ homebrew_cask_fonts }}"
