---
# awscli
# - name: install awscli pip3
#   pip:
#     name: awscli
#     executable: pip3
#     state: latest

# aws2
- name: confirm aws2 exists
  stat:
    path: /usr/local/bin/aws
    get_checksum: false
    get_md5: false
  register: aws2_exists

- name: download aws2
  shell: >
    curl -L "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
  when: not aws2_exists.stat.exists

- name: unzip aws2
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/awscliv2
    remote_src: yes
  when: not aws2_exists.stat.exists

# install to /usr/local/aws by default.
# symlink to /usr/local/bin by default.
- name: install aws2
  become: yes
  shell: >
    ./aws/install --update
  when: not aws2_exists.stat.exists

# eksctl
- name: confirm eksctl exists
  stat:
    path: /usr/local/bin/eksctl
    get_checksum: false
    get_md5: false
  register: eksctl_exists

- name: download eksctl
  shell: >
    curl -L "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" -o /tmp/eksctl_amd64.tar.gz
  when: not eksctl_exists.stat.exists

- name: unzip eksctl
  become: yes
  unarchive:
    src: /tmp/eksctl_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  when: not eksctl_exists.stat.exists

- name: remove eksctl tmp
  file:
    path: /tmp/eksctl_$(uname -s)_amd64.tar.gz
    state: absent
  when: not eksctl_exists.stat.exists

- name: chmod eksctl
  become: yes
  file:
    path: /usr/local/bin/eksctl
    mode: a+x

# aws-iam-authenticator
# ref: https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/install-aws-iam-authenticator.html
# TODO: version mis match with `aws-iam-authenticator version` and download url :(
- name: confirm aws-iam-authenticator exists
  stat:
    path: /usr/local/bin/aws-iam-authenticator
    get_checksum: false
    get_md5: false
  register: aws_iam_authenticator_exists

- name: download aws-iam-authenticator
  become: yes
  shell: curl -L "https://amazon-eks.s3-us-west-2.amazonaws.com/{{ aws_iam_authenticator_version }}/{{ aws_iam_authenticator_date }}/bin/linux/amd64/aws-iam-authenticator" -o /usr/local/bin/aws-iam-authenticator
  when: not aws_iam_authenticator_exists.stat.exists

- name: chmod aws-iam-authenticator
  become: yes
  file:
    path: /usr/local/bin/aws-iam-authenticator
    mode: a+x
