---

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes

- name: install awscli
  become: yes
  apt:
    pkg: awscli

- name: install awscli pip3
  pip:
    name: awscli
    executable: pip3
    extra_args: --upgrade --user
    state: latest
