# check at https://github.com/a8m/envsubst/releases
- name: check envsubst2 exists
  stat:
    path: /usr/local/bin/envsubst2
  register: stat_result

- name: download envsubst2
  become: yes
  get_url:
    url: https://github.com/a8m/envsubst/releases/download/v{{ envsubst2_download_version }}/envsubst-Linux-x86_64
    dest: "/usr/local/bin/envsubst2"
  register: download_envsubst2
  when: not stat_result.stat.exists

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/envsubst2
    mode: "a+x"
  when: not stat_result.stat.exists

- name: confirm envsubst2 exists
  shell: ls /usr/local/bin/envsubst2
  changed_when: false
