---

# kubectl
- name: confirm kubectl exists
  stat:
    path: /usr/local/bin/kubectl
    get_checksum: false
    get_md5: false
  register: kubectl_exists
  
- name: download kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: "{{ ansible_home }}/kubectl"
  register: download_kubectl
  when: not kubectl_exists.stat.exists

- name: copy kubectl
  become: yes
  copy:
    src: "{{ ansible_home }}/kubectl"
    dest: /usr/local/bin
  when: not kubectl_exists.stat.exists

- name: remove kubectl
  file:
    state: absent
    path: "{{ ansible_home }}/kubectl"
  when: download_kubectl is succeeded

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/kubectl
    mode: '0755'

# kubeadm
- name: add kube apt
  become: yes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: add kubeadm apt_key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes

- name: install kubeadm
  become: yes
  apt:
    pkg: kubeadm

# helm
- name: confirm helm exists
  stat:
    path: /usr/local/bin/helm
    get_checksum: false
    get_md5: false
  register: helm_exists
  
- name: download helm
  get_url:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
    dest: "{{ ansible_home }}/helm.tar.gz"
  register: download_helm
  when: not helm_exists.stat.exists

- name: unarchive helm
  command: tar -zxvf "{{ ansible_home }}/helm.tar.gz"
  args:
    chdir: "{{ ansible_home }}/"
  register: unarchive_helm
  when: not helm_exists.stat.exists

- name: copy helm
  become: yes
  copy:
    src: "{{ ansible_home }}/linux-amd64/helm"
    dest: /usr/local/bin
  when: not helm_exists.stat.exists

- name: copy tiller
  become: yes
  copy:
    src: "{{ ansible_home }}/linux-amd64/tiller"
    dest: /usr/local/bin
  when: not helm_exists.stat.exists

- name: remove helm
  file:
    state: absent
    path: "{{ ansible_home }}/helm.tar.gz"
  when: download_helm is succeeded

- name: remove helm
  file:
    state: absent
    path: "{{ ansible_home }}/helm"
  when: unarchive_helm is succeeded

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/helm
    mode: '0755'

- name: change file permissions
  become: yes
  file:
    path: /usr/local/bin/tiller
    mode: '0755'

# kubectx
- name: clone kubectx
  become: yes
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: "{{ ansible_home}}/github/kubectx"
    accept_hostkey: yes
  when: not check_repos.stat.exists

- name: create kubectx symlinks
  become: yes
  file:
    src: "{{ ansible_home}}/github/kubectx/kubectx"
    dest: "/usr/local/bin/kubectx"
    state: link

