---
- name: "{{ ansible_role_name}}: check installed"
  shell: pulumi version | grep v{{ pulumi_version }}
  register: pulumi_exists
  changed_when: false
  ignore_errors: yes

# https://www.pulumi.com/docs/get-started/install/versions/
- name: "{{ ansible_role_name}}: download"
  shell: curl -Ls "https://get.pulumi.com/releases/sdk/pulumi-v{{ pulumi_version }}-linux-x64.tar.gz" -o /tmp/pulumi-linux-x64.tar.gz
  when: pulumi_exists is failed

- name: "{{ ansible_role_name}}: unzip"
  shell: tar -zxvf /tmp/pulumi-linux-x64.tar.gz
  args:
    chdir: "/tmp"
  when: pulumi_exists is failed

- name: "{{ ansible_role_name}}: copy"
  become: yes
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: a+x
  with_fileglob:
    - "/tmp/pulumi/pulumi*"
  when: pulumi_exists is failed

- name: "{{ ansible_role_name}}: remove tmp"
  file:
    path: /tmp/pulumi-linux-x64.tar.gz
    state: absent
  when: pulumi_exists is failed

- name: "{{ ansible_role_name}}: remove tmp directory"
  file:
    path: "/tmp/pulumi/"
    state: absent
  when: pulumi_exists is failed
