---
- name: check pulumi installed
  shell: pulumi version | grep v{{ pulumi_version }}
  register: pulumi_exists
  changed_when: false
  ignore_errors: yes

# https://www.pulumi.com/docs/get-started/install/versions/
- name: download pulumi
  shell: curl -Ls "https://get.pulumi.com/releases/sdk/pulumi-v{{ pulumi_version }}-linux-x64.tar.gz" -o /tmp/pulumi-linux-x64.tar.gz
  warn: false
  when: pulumi_exists is failed

- name: unzip pulumi
  shell: tar -zxvf /tmp/pulumi-linux-x64.tar.gz
  args:
    chdir: "/tmp"
  when: pulumi_exists is failed

- name: copy pulumi
  become: yes
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: a+x
  with_fileglob:
    - "/tmp/pulumi/pulumi*"
  when: pulumi_exists is failed

- name: remove pulumi tmp
  file:
    path: /tmp/pulumi-linux-x64.tar.gz
    state: absent
  when: pulumi_exists is failed

- name: remove pulumi tmp directory
  file:
    path: "/tmp/pulumi/"
    state: absent
  when: pulumi_exists is failed
