---
- name: Create .nodebrew directory
  ansible.builtin.file:
    path: "$HOME/.nodebrew"
    state: directory

- name: Create .nodebrew src directory
  ansible.builtin.file:
    path: "$HOME/.nodebrew/src"
    state: directory

- name: check node.js installed
  shell: $SHELL -lc "which node"
  ignore_errors: True
  changed_when: nodejs_installed.rc > 0
  register: nodejs_installed

- name: check installed node.js version
  shell: $SHELL -lc "nodebrew ls | grep {{ nodebrew_nodejs_version }}"
  ignore_errors: True
  changed_when: nodejs_target_version_exist.rc > 0
  when: nodejs_installed is success
  register: nodejs_target_version_exist

- name: install node.js
  shell: $SHELL -lc "nodebrew install-binary {{ nodebrew_nodejs_version }}"
  when: (nodejs_installed is failed) or (nodejs_target_version_exist is failed)

- name: npm update
  shell: $SHELL -lc "npm update -g npm"
  when: nodebrew_npm_update
  changed_when: npm_updated.stdout != ''
  register: npm_updated

- name: install npm packges
  npm:
    name: "{{ item.name }}"
    global: "{{ item.global|default('yes') }}"
  with_items: "{{ npm_pacakges }}"
