---

# installation procedure for ubuntu
# ref: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

- name: modify sources list for azcli 
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
    state: present
    filename: azure-cli.list

- name: Add an Apt signing key for azcli
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes

- name: apt-get install azcli
  become: yes
  apt:
    pkg: [
      apt-transport-https,
      azure-cli,
    ]
    state: present
    update_cache: yes