---
- name: check  terraform installed
  ansible.builtin.shell: set -o pipefail && tfenv list | grep {{ terraform_version }}
  args:
    executable: /bin/bash
  register: tfenv_version
  changed_when: false
  ignore_errors: true

- name: install terraform
  ansible.builtin.command: tfenv install {{ terraform_version }}
  when: tfenv_version is failed
