---

- name: pickup installed terraform versions
  shell: tfenv list | grep {{ terraform_version }}
  register: tfenv_version
  changed_when: false
  ignore_errors: yes

- name: install terraform
  shell: tfenv install {{ terraform_version }}
  when: tfenv_version is failed
