# bombardier
- name: pickup installed bombardier versions
  shell: bombardier --version 2>&1 | head -n 1 | grep {{ bombardier_version }}
  register: bombardier_exists
  changed_when: false
  ignore_errors: yes

- name: download bombardier
  become: yes
  shell: curl -L "https://github.com/codesenberg/bombardier/releases/download/{{ bombardier_version }}/bombardier-linux-amd64" -o /usr/local/bin/bombardier
  register: download_bombardier
  when: bombardier_exists is failed

- name: chmod bombardier
  become: yes
  file:
    path: /usr/local/bin/bombardier
    mode: a+x
