# bombardier
- name: pickup installed bombardier versions
  shell: bombardier version | grep {{ bombardier_version }}
  register: bombardier_exists
  changed_when: false
  ignore_errors: yes

- name: download bombardier
  shell: >
    curl -L "https://github.com/codesenberg/bombardier/releases/download/{{ bombardier_version }}/bombardier-linux-amd64" -o /tmp/bombardier
  register: download_bombardier
  when: bombardier_exists is failed

- name: copy bombardier
  become: yes
  copy:
    src: /tmp/bombardier
    dest: /usr/local/bin
  when: download_bombardier is succeeded

- name: remove kubectl
  file:
    state: absent
    path: "/tmp/bombardier"
  when: download_bombardier is succeeded

- name: chmod bombardier
  become: yes
  file:
    path: /usr/local/bin/bombardier
    mode: a+x
