---
- name: install docker
  become: yes
  apt:
      pkg: docker.io
      update_cache: yes

- name: confirm docker-compose exists
  stat:
      path: /usr/local/bin/docker-compose
      get_checksum: false
      get_md5: false
  register: dockercompose_exists

- name: download docker-compose
  become: yes
  shell: >
      curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  when: not dockercompose_exists.stat.exists

- name: chmod docker-compose
  become: yes
  file:
      path: /usr/local/bin/docker-compose
      mode: a+x
