- name: "Install aws cli"
  include: include_role/install_docker.yaml
  with_items: "{{ docker }}"
  loop_control:
    loop_var: args

- name: "Install eksctl"
  include: include_role/install_dockercompose.yaml
  with_items: "{{ docker_compose }}"
  loop_control:
    loop_var: args
