- name: "Install guitarrapc bucket"
  scoop_bucket_install:
    state: present
    bucket: guitarrapc
    source: https://github.com/guitarrapc/scoop-bucket.git

- name: "Install guitarrapc tools"
  scoop_install:
    state: present
    bucket: guitarrapc
    name:
      - bombardier
      - conftest
      - ctop
      - DejaVuSansMono-Bront
      - ecspresso
      - ghz
      - googlechrome-stable # fork version and use https://github.com/42wim/chromeupdates as update source.
      - opa
      - py
      - qttabbar-beta # for Windows 11
