- name: "Install guitarrapc bucket"
  scoop_bucket_install:
    state: present
    bucket: guitarrapc
    source: https://github.com/guitarrapc/scoop-bucket.git

- name: "Install guitarrapc tools"
  scoop_install:
    state: present
    bucket: guitarrapc
    name:
      # - 0xProto # no more font
      - bombardier
      - browserouter
      - conftest
      - ctop
      # - DejaVuSansMono-Bront # no more font
      - ecspresso
      - ghz
      - googlechrome-stable # fork version and use https://github.com/42wim/chromeupdates as update source.
      - opa
      - py
      - yamlfmt

- name: "Uninstall guitarrapc tools"
  scoop_install:
    state: absent
    bucket: guitarrapc
    name:
      - qttabbar-beta # for Windows 11, but Windows 11 has tab explorer by default.
