- name: "Install guitarrapc bucket"
  scoop_bucket_install:
    state: present
    bucket: guitarrapc
    source: https://github.com/guitarrapc/scoop-bucket.git

- name: "Install guitarrapc tools"
  scoop_install:
    state: present
    bucket: guitarrapc
    name:
      - actionlint # will move to extras when pr merged.
      - bombardier
      - conftest
      - ctop
      - DejaVuSansMono-Bront
      - ecspresso
      - ghz
      - py
      - qttabbar
      - qttabbar-patch
