- name: "Install bear bucket"
  scoop_bucket_install:
    state: present
    bucket: ba230t
    source: https://github.com/ba230t/scoop-bucket.git

- name: "Install bear tools"
  scoop_install:
    state: present
    bucket: ba230t
    name:
      - git-secrets
