# explict docker installation. No Docker for Windows mapping.
- name: "Install docker"
  include: ../include_role/ubuntu/install_docker_wsl2.yaml

- name: "Install docker-compose"
  include: ../include_role/ubuntu/install_binary.yaml
  with_items: "{{ docker_compose }}"
  loop_control:
    loop_var: args
