- name: "Link .aws credential"
  ansible.builtin.include_tasks: ../include_role/ubuntu/credentials_aws.yaml
  with_items: "{{ aws_config }}"
  loop_control:
    loop_var: args

- name: "Link .azure credential"
  ansible.builtin.include_tasks: ../include_role/ubuntu/credentials_azure.yaml
  with_items: "{{ azure_config }}"
  loop_control:
    loop_var: args

- name: "Link .kube credential"
  ansible.builtin.include_tasks: ../include_role/ubuntu/credentials_kube.yaml
  with_items: "{{ kube_config }}"
  loop_control:
    loop_var: args
