---
- name: Create github directory
  ansible.builtin.file:
    path: "{{ base_path }}"
    state: directory
    force: true

- name: Clone dotfiles
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    force: true
  with_items: "{{ repository }}"

- name: Create symlinks
  command: bash -lc "{{ run_dotfiles }}"
  changed_when: false
  register: dotfiles

- debug: msg="{{ dotfiles.stdout_lines }}"
