# https://github.com/lukesampson/scoop-extras
- name: "Install Extra tools"
  scoop_install_extras:
    state: present
    name:
      - azure-cli
      - azure-functions-core-tools
      - dnspy
      - everything
      - fiddler
      - gitkraken
      - heidisql
      - kdiff3
      - linqpad
      - ngrok
      - slack
      - vscode
