# https://github.com/lukesampson/scoop-extras
- name: "Install extras bucket"
  scoop_bucket_install:
    state: present
    bucket: extras

- name: "Install extras tools"
  scoop_install:
    state: present
    bucket: extras
    name:
      - everything
      - fork
      - gcloud
      - gitkraken
      #- googlechrome # dont't want change userprofile location. use self provided.
      - heidisql
      - ilspy
      - kdiff3
      - linqpad
      - mobaxterm
      - msbuild-structured-log-viewer
      - streamdeck
      - slack
      - vscode
      - vswhere

- name: "Uninstall extras tools"
  scoop_install:
    state: absent
    bucket: extras
    name:
      - wiztree # commercial use is now required payment.
