# https://github.com/lukesampson/scoop-extras
- name: "Install extras bucket"
  scoop_bucket_install:
    state: present
    bucket: extras

- name: "Install extras tools"
  scoop_install:
    state: present
    bucket: extras
    name:
      - azure-cli
      - dnspy
      - everything
      - fiddler
      - fontbase
      - gitkraken
      - googlechrome
      - hack-font
      - kdiff3
      - linqpad
      - powertoys
      - slack
      - vscode
      - vswhere
      - wiztree
