# https://github.com/lukesampson/scoop-extras
- name: "Install extras bucket"
  scoop_bucket_install:
    state: present
    bucket: extras

- name: "Install extras tools"
  scoop_install:
    state: present
    bucket: extras
    name:
      - actionlint
      - everything
      - fork
      - gitkraken
      #- googlechrome # too old and won't update since 91. stop use it and use self update.
      - hack-font
      - ilspy
      - kdiff3
      - lens
      - linqpad
      - mobaxterm
      - streamdeck
      - slack
      - vscode
      - vswhere
      - wiztree
