# https://github.com/lukesampson/scoop-extras
- name: "Install extras bucket"
  scoop_bucket_install:
    state: present
    bucket: extras

- name: "Install extras tools"
  scoop_install:
    state: present
    bucket: extras
    name:
      - azure-cli
      - azure-functions-core-tools
      - dnspy
      - everything
      - fiddler
      - gitkraken
      - googlechrome
      - hack-font
      - heidisql
      - kdiff3
      - linqpad
      - postman
      - slack
      - vscode
      - vswhere
