# defaults
- name: "Set Screen Defaults"
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ screen_settings }}"

- name: "Set Trackpad Defaults"
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ trackpad_settings }}"

- name: "Set Finder Defaults"
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ finder_settings }}"

- name: "Set Dock Defaults"
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ dock_settings }}"

- name: "Set Terminal Defaults"
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ terminal_settings }}"

# pam
- name: enable touchid for sudo Authentication
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sudo
    insertafter: "^# sudo: auth account password session"
    line: "auth       sufficient     pam_tid.so"
  when: lookup('env', "CI", default="false") != "true"
