- name: local-dev ubuntu setup
  hosts: 'local'
  become: no
  pre_tasks:
    - name: Get ansible_user home directory
      become: no
      shell: 'getent passwd "{{ansible_user_id}}" | cut -d: -f6'
      register: ansible_home_result
      changed_when: false
      tags: always
    - name: Set the fact for the other scripts to use
      set_fact: ansible_home='{{ansible_home_result.stdout}}'
    - name: debug home path
      debug:
        msg: "{{ ansible_home }}"
  roles:
    - { role: 'direnv', tags: [direnv] }
    - { role: 'awscli', tags: [awscli] }
    - { role: 'azcli', tags: [azcli] }
    - { role: 'python', tags: [python] }
    - { role: 'terraform', tags: [terraform] }
    - { role: 'docker', tags: [docker] }
    - { role: 'tools', tags: [tools] }
    - { role: 'dotfiles', tags: [dotfiles] }

# ansible-playbook -i hosts site.yml --ask-sudo-pass