# Configure needrestart for WSL Ubuntu. This is needed for WSL2 to installing packages unattended.
# ----------------
# ```roles/main.yaml
# - name: "Configure needrestart"
#   ansible.builtin.include_tasks: ../include_role/ubuntu/configure_needrestart.yaml
# ```

- name: "needrestart - check OS is using needrestart"
  become: true
  ansible.builtin.stat:
    path: /usr/sbin/needrestart
  register: needrestart_exists

- name: "needrestart - remove needrestart"
  become: true
  ansible.builtin.apt:
    pkg: "needrestart"
    state: absent
  register: apt
  until: "apt is not failed"
  retries: 2 # wsl1 failed first apt on Ubuntu-22.04
  when: (is_wsl1 == "1") and needrestart_exists.stat.exists

- name: "needrestart - place custom conf.d"
  become: true
  ansible.builtin.copy:
    dest: /etc/needrestart/conf.d/99_ansible.conf
    content: |
      # use stdin to select restart service
      $nrconf{ui} = 'NeedRestart::UI::stdio';
      # control restart service
      $nrconf{kernelhints} = '0';
      $nrconf{ucodehints} = 0;
      $nrconf{restart} = 'a';
    mode: "0644"
  when: (is_wsl2 == "1") and needrestart_exists.stat.exists
