- name: "configure needrestart - remove needrestart"
  become: true
  apt:
    pkg: "needrestart"
    state: absent
  when: is_wsl1 == "1"

- name: "needrestart - check OS is using needrestart"
  become: true
  stat:
    path: /usr/sbin/needrestart
  register: needrestart_exists
  when: is_wsl2 == "1"

- name: "needrestart - place custom conf.d"
  become: true
  copy:
    dest: /etc/needrestart/conf.d/99_ansible.conf
    content: |
      # use stdin to select restart service
      $nrconf{ui} = 'NeedRestart::UI::stdio';
      # control restart service
      $nrconf{kernelhints} = '0';
      $nrconf{ucodehints} = 0;
      $nrconf{restart} = 'a';
  when: (is_wsl2 == "1") and needrestart_exists.stat.exists
