# .azure
- name: ".azure - check src Win path {{ args.win_path }} exists"
  ansible.builtin.stat:
    path: "{{ args.win_path }}"
  register: win_azure_stat_result

- name: ".azure - check Linux path {{ args.linux_path }} is link"
  ansible.builtin.stat:
    path: "{{ ansible_home }}/{{ args.linux_path }}"
  register: linux_azure_link

- name: ".azure - delete linux default folder"
  file:
    path: "{{ ansible_home }}/{{ args.linux_path }}"
    state: absent
  when: (win_azure_stat_result.stat.exists) and (linux_azure_link.stat.exists) and (not linux_azure_link.stat.islnk)

- name: ".azure - create symlinks with Win path"
  file:
    src: "{{ args.win_path }}"
    dest: "{{ ansible_home }}/{{ args.linux_path }}"
    state: link
  when: win_azure_stat_result.stat.exists
