# Symlink host .azure to WSL .azure
#
# See below for an example of how to use this role.
# ```vars/main.yaml
# azure_config:
#   - linux_path: .azure
#     win_path: "/mnt/c/Users/{{ ansible_user_id }}/.azure"
# ````
#
# ```roles/main.yaml
# - name: "Link .azure credential"
#   ansible.builtin.include_tasks: ../include_role/ubuntu/credentials_azure.yaml
#   with_items: "{{ azure_config }}"
#   loop_control:
#     loop_var: args
# ```
# .azure
- name: ".azure - check src Win path {{ args.win_path }} exists"
  ansible.builtin.stat:
    path: "{{ args.win_path }}"
  register: win_azure_stat_result

- name: ".azure - check Linux path {{ args.linux_path }} is link"
  ansible.builtin.stat:
    path: "{{ ansible_home }}/{{ args.linux_path }}"
  register: linux_azure_link

- name: ".azure - delete linux default folder"
  ansible.builtin.file:
    path: "{{ ansible_home }}/{{ args.linux_path }}"
    state: absent
  when: (win_azure_stat_result.stat.exists) and (linux_azure_link.stat.exists) and (not linux_azure_link.stat.islnk)

- name: ".azure - create symlinks with Win path"
  ansible.builtin.file:
    src: "{{ args.win_path }}"
    dest: "{{ ansible_home }}/{{ args.linux_path }}"
    state: link
  when: win_azure_stat_result.stat.exists
