# Symlink host .aws to WSL .aws
# see: # https://github.com/aws/aws-cli/releases
#
# See below for an example of how to use this role.
# ```vars/main.yaml
# aws_config:
#   - linux_path: .aws/credentials
#     win_path: "/mnt/c/Users/{{ ansible_user_id }}/.aws/credentials"
#   - linux_path: .aws/config
#     win_path: "/mnt/c/Users/{{ ansible_user_id }}/.aws/config"
# ````
#
# ```roles/main.yaml
# - name: "Link .aws credential"
#   ansible.builtin.include_tasks: ../include_role/ubuntu/credentials_aws.yaml
#   with_items: "{{ aws_config }}"
#   loop_control:
#     loop_var: args
# ```

- name: "aws - create .aws directory"
  ansible.builtin.file:
    path: "{{ ansible_home }}/.aws"
    state: directory
    mode: "0755"

- name: ".aws - check src Win path {{ args.win_path }} exists"
  ansible.builtin.stat:
    path: "{{ args.win_path }}"
  register: win_aws_stat_result

- name: ".aws - check Linux path {{ args.linux_path }} is link"
  ansible.builtin.stat:
    path: "{{ ansible_home }}/{{ args.linux_path }}"
  register: linux_aws_link

- name: ".aws - delete linux default file"
  ansible.builtin.file:
    path: "{{ ansible_home }}/.aws/credentials"
    state: absent
  when: (win_aws_stat_result.stat.exists) and (linux_aws_link.stat.exists) and (not linux_aws_link.stat.islnk)

- name: ".aws - create symlinks with Win path"
  ansible.builtin.file:
    src: "{{ args.win_path }}"
    dest: "{{ ansible_home }}/{{ args.linux_path }}"
    state: link
  when: win_aws_stat_result.stat.exists
