# https://github.com/aws/aws-cli/releases
- name: "aws - create .aws directory"
  ansible.builtin.file:
    path: "{{ ansible_home }}/.aws"
    state: directory

- name: ".aws - check src Win path {{ args.win_path }} exists"
  ansible.builtin.stat:
    path: "{{ args.win_path }}"
  register: win_aws_stat_result

- name: ".aws - check Linux path {{ args.linux_path }} is link"
  ansible.builtin.stat:
    path: "{{ ansible_home }}/{{ args.linux_path }}"
  register: linux_aws_link

- name: ".aws - delete linux default file"
  ansible.builtin.file:
    path: "{{ ansible_home }}/.aws/credentials"
    state: absent
  when: (win_aws_stat_result.stat.exists) and (linux_aws_link.stat.exists) and (not linux_aws_link.stat.islnk)

- name: ".aws - create symlinks with Win path"
  ansible.builtin.file:
    src: "{{ args.win_path }}"
    dest: "{{ ansible_home }}/{{ args.linux_path }}"
    state: link
  when: win_aws_stat_result.stat.exists
