# Symlink host .kube to WSL .kube
#
# See below for an example of how to use this role.
# ```vars/main.yaml
# kube_config:
#   - linux_path: .kube/config
#     win_path: "/mnt/c/Users/{{ ansible_user_id }}/.kube/config"
# ````
#
# ```roles/main.yaml
# - name: "Link .kube credential"
#   ansible.builtin.include_tasks: ../include_role/ubuntu/credentials_kube.yaml
#   with_items: "{{ kube_config }}"
#   loop_control:
#     loop_var: args
# ```

# .kube/config
- name: ".kube - create ~/.kube directory"
  ansible.builtin.file:
    path: "{{ ansible_home }}/.kube"
    state: directory
    mode: "0755"

- name: ".kube - check src Win path {{ args.win_path }} exists"
  ansible.builtin.stat:
    path: "{{ args.win_path }}"
  register: win_kube_stat_result

- name: ".kube - check Linux path {{ args.linux_path }} is link"
  ansible.builtin.stat:
    path: "{{ ansible_home }}/{{ args.linux_path }}"
  register: linux_kube_link

- name: ".kube - delete linux default file"
  ansible.builtin.file:
    path: "{{ ansible_home }}/{{ args.linux_path }}"
    state: absent
  when: (win_kube_stat_result.stat.exists) and (linux_kube_link.stat.exists) and (not linux_kube_link.stat.islnk)

- name: ".kube - create symlinks with Win path"
  ansible.builtin.file:
    src: "{{ args.win_path }}"
    dest: "{{ ansible_home }}/{{ args.linux_path }}"
    state: link
  when: win_kube_stat_result.stat.exists
