# Install azure-cli.
# see: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt
#
# See below for an example of how to use this role.
# ```roles/main.yaml
# - name: "azure - Install azure cli"
#   ansible.builtin.include_tasks: ../include_role/ubuntu/install_azurecli.yaml
# ```

- name: "azure-cli - make sure install prerequisites"
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - lsb-release
      # - gnupg # no need.
    update_cache: true
  register: apt
  until: "apt is not failed"
  retries: 2 # wsl1 failed first apt on Ubuntu-22.04

- name: "azure-cli - import azure-cli apt key"
  become: true
  ansible.builtin.shell: |
    set -o pipefail && curl -sL https://packages.microsoft.com/keys/microsoft.asc |
      gpg --dearmor |
      sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
  args:
    executable: /bin/bash
  changed_when: false

- name: "azure-cli - add repo for Ubuntu"
  become: true
  # $(lsb_release -cs) = {{ ansible_distribution_release }}
  ansible.builtin.shell: set -o pipefail && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  args:
    executable: /bin/bash
  changed_when: false

- name: "azure-cli - install"
  become: true
  ansible.builtin.apt:
    pkg: azure-cli
    state: latest
    update_cache: true
  register: apt
  until: "apt is not failed"
  retries: 2 # wsl1 failed first apt on Ubuntu-22.04
