- name: "binary_targz ({{ args.name }}) - check installed"
  shell: "{{ args.name }} {{ args.version_arg }} 2>&1 | grep {{ args.version }}"
  register: binary_targz_exists
  changed_when: false
  ignore_errors: true

- name: "binary_targz ({{ args.name }}) - tmp directory"
  file:
    path: "/tmp/{{ args.name }}"
    state: directory
  when: binary_targz_exists is failed

- name: "binary_targz ({{ args.name }}) - download"
  get_url:
    url: "{{ args.download_url }}"
    dest: "/tmp/{{ args.name }}/{{ args.name }}.tar.gz"
  when: binary_targz_exists is failed

- name: "binary_targz ({{ args.name }}) - unarchive"
  unarchive:
    src: "/tmp/{{ args.name }}/{{ args.name }}.tar.gz"
    dest: /tmp/{{ args.name }}
    remote_src: true
  when: binary_targz_exists is failed

- name: "binary_targz ({{ args.name }}) - copy"
  become: true
  ansible.builtin.copy:
    src: "/tmp/{{ args.name }}/{{ args.copy_root }}{{ item }}"
    dest: "{{ args.dest_override | default('/usr/local/bin/') }}"
    mode: "a+x"
    remote_src: true
  with_items: "{{ args.binaries }}"
  when: binary_targz_exists is failed

- name: "binary_targz ({{ args.name }}) - remove temp files"
  file:
    state: absent
    path: /tmp/{{ args.name }}
  when: binary_targz_exists is failed
