# Install latest golang. https://launchpad.net/%7Elongsleep/+archive/ubuntu/golang-backports
#
# See below for an example of how to use this role.
# ```yaml
# - name: "Go - Install go"
#   ansible.builtin.include_tasks: ../include_role/ubuntu/install_go.yaml
# ```

- name: "go - Add Golang PPA GPG key"
  become: true
  ansible.builtin.apt_key:
    id: "C631127F87FA12D1"
    keyserver: "keyserver.ubuntu.com"
    keyring: /etc/apt/trusted.gpg.d/longsleep.gpg
    state: present

- name: "go - Add ppa:longsleep/golang-backports ppa repository"
  become: true
  ansible.builtin.apt_repository:
    # not ppa shorhand, write with deb
    repo: "deb http://ppa.launchpad.net/longsleep/golang-backports/ubuntu {{ ansible_distribution_release }} main"
    filename: "longsleep-golang-backports"
    keyring: /etc/apt/trusted.gpg.d/longsleep.gpg
    state: present

- name: "go - Install go"
  become: true
  ansible.builtin.apt:
    name: "golang-{{ go.version }}"
    state: latest
    update_cache: true
  register: apt
  until: "apt is not failed"
  retries: 2 # wsl1 failed first apt on Ubuntu-22.04
