- name: "anyenv - Clone & Fetch repo"
  git:
    repo: "https://github.com/anyenv/anyenv"
    dest: "{{ ansible_home }}/.anyenv"

- name: "anyenv - Create symlinks"
  become: true
  ansible.builtin.file:
    src: "{{ ansible_home }}/.anyenv/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - anyenv

- name: "anyenv - check ~/.config/anyenv/anyenv-install exists"
  ansible.builtin.stat:
    path: "{{ ansible_home }}/.config/anyenv/anyenv-install"
  register: anyenv_confi_exists

- name: "anyenv - install --init"
  ansible.builtin.shell: yes | anyenv install --init
  when: not anyenv_confi_exists.stat.exists
  changed_when: false

- name: "anyenv - install goenv"
  ansible.builtin.shell: anyenv install goenv --skip-existing
  changed_when: false
  when: args.goenv == "true"

- name: "anyenv - install nodenv"
  ansible.builtin.shell: anyenv install nodenv --skip-existing
  changed_when: false
  when: args.nodenv == "true"

- name: "anyenv - install pyenv"
  ansible.builtin.shell: anyenv install pyenv --skip-existing
  changed_when: false
  when: args.pyenv == "true"
