- name: "azure-cli - make sure install prerequisites"
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - lsb-release
      # - gnupg # no need.
    update_cache: true

- name: "azure-cli - import azure-cli apt key"
  become: true
  ansible.builtin.shell: |
    curl -sL https://packages.microsoft.com/keys/microsoft.asc |
      gpg --dearmor |
      sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
  args:
    warn: false
  changed_when: false

- name: "azure-cli - add repo for Ubuntu"
  become: true
  # $(lsb_release -cs) = {{ ansible_distribution_release }}
  ansible.builtin.shell: echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  changed_when: false

- name: "azure-cli - install"
  become: true
  ansible.builtin.apt:
    pkg: azure-cli
    state: latest
    update_cache: true
