# Install kubectl plugin via krew.
#   * Dependencies: install_krew.yaml
#
# See below for an example of how to use this role.
# ```yaml
# krew_plugins:
#   - name: explore # https://github.com/keisku/kubectl-explore A better kubectl explain with the fuzzy finder
#     install_check_arg: "--help"
#   - name: fuzzy # https://github.com/d-kuro/kubectl-fuzzy Instead of specifying full resource names to kubectl commands, you can choose them from an interactive list that you can filter by typing a few characters.
#     install_check_arg: "--help"
#   - name: get-all # https://github.com/corneliusweig/ketall Like `kubectl get all`, but get really all resources
#     install_check_arg: "--help"
# ```
#
# ```yaml
# - name: "krew Plugins - Install krew kubectl plugins"
#   ansible.builtin.include_tasks: ../include_role/ubuntu/install_krew_plugin.yaml
#   with_items: "{{ krew_plugins }}"
#   loop_control:
#     loop_var: args
# ```

- name: "kubectl_plugin ({{ args.name }}) - check already installed"
  ansible.builtin.command: "kubectl {{ args.name }} {{ args.install_check_arg }} 2>&1"
  environment:
    # kubectl is install via asdf
    # require re-login shell for 1st install, let's manual export shellenv and use it
    PATH: "{{ ansible_home }}/.local/share/aquaproj-aqua/bin:{{ ansible_home }}/.krew/bin:{{ ansible_env.PATH }}"
    AQUA_GLOBAL_CONFIG: "{{ ansible_home }}/.config/aquaproj-aqua/aqua.yaml"
  register: kubectl_plugin_exists
  changed_when: kubectl_plugin_exists.rc != 0
  ignore_errors: true

- name: "kubectl_plugin ({{ args.name }}) - install"
  ansible.builtin.command: kubectl krew install {{ args.name }}
  environment:
    # kubectl is install via asdf
    # require re-login shell for 1st install, let's manual export shellenv and use it
    PATH: "{{ ansible_home }}/.local/share/aquaproj-aqua/bin:{{ ansible_home }}/.krew/bin:{{ ansible_env.PATH }}"
    AQUA_GLOBAL_CONFIG: "{{ ansible_home }}/.config/aquaproj-aqua/aqua.yaml"
  register: krew_plugin_install
  changed_when: krew_plugin_install.rc != 0
  when: kubectl_plugin_exists is failed

- name: "kubectl_plugin ({{ args.name }}) - check installed"
  ansible.builtin.command: "kubectl {{ args.name }} {{ args.install_check_arg }} 2>&1"
  environment:
    # kubectl is install via asdf
    # require re-login shell for 1st install, let's manual export shellenv and use it
    PATH: "{{ ansible_home }}/.local/share/aquaproj-aqua/bin:{{ ansible_home }}/.krew/bin:{{ ansible_env.PATH }}"
    AQUA_GLOBAL_CONFIG: "{{ ansible_home }}/.config/aquaproj-aqua/aqua.yaml"
  changed_when: false
  when: kubectl_plugin_exists is failed
