- name: "git_tool - ({{ args.name }}) - clone"
  become: true
  ansible.builtin.git:
    repo: "{{ args.git_https_url }}"
    dest: "{{ ansible_home }}/github/{{ args.name }}"
    accept_hostkey: true

- name: "git_tool - ({{ args.name }}) - create symlinks"
  become: true
  ansible.builtin.file:
    src: "{{ ansible_home }}/github/{{ args.name }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items: "{{ args.link_binaries }}"
  when: (not ansible_check_mode) and (args.link_binaries is defined)
