- name: "anyenv - Clone & Fetch repo"
  ansible.builtin.git:
    repo: "https://github.com/anyenv/anyenv"
    dest: "{{ ansible_home }}/.anyenv"

- name: "anyenv - Create symlinks"
  become: true
  ansible.builtin.file:
    src: "{{ ansible_home }}/.anyenv/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - anyenv

- name: "anyenv - check ~/.config/anyenv/anyenv-install exists"
  ansible.builtin.stat:
    path: "{{ ansible_home }}/.config/anyenv/anyenv-install"
  register: anyenv_confi_exists

- name: "anyenv - install --init"
  ansible.builtin.shell: set -o pipefail && yes | anyenv install --init
  args:
    executable: /bin/bash
  when: not anyenv_confi_exists.stat.exists
  changed_when: false

- name: "anyenv - install goenv"
  ansible.builtin.command: anyenv install goenv --skip-existing
  register: anyenv_install_goenv
  changed_when: anyenv_install_goenv.rc != 0
  when: args.goenv == "true"

- name: "anyenv - install nodenv"
  ansible.builtin.command: anyenv install nodenv --skip-existing
  register: anyenv_install_nodeenv
  changed_when: anyenv_install_nodeenv.rc != 0
  when: args.nodenv == "true"

- name: "anyenv - install pyenv"
  ansible.builtin.command: anyenv install pyenv --skip-existing
  register: anyenv_install_pyenv
  changed_when: anyenv_install_pyenv.rc != 0
  when: args.pyenv == "true"
