# Install gpg.
# See below for an example of how to use this role.
# ----------------
# ```yaml
# - name: "git - Install git cli"
#   ansible.builtin.include_tasks: ../include_role/ubuntu/install_git.yaml
# ```

# if wsl2 docker is enabled, gpg will be locate in /usr/bin/gpg
- name: "gpg - check /usr/bin/gpg exists"
  ansible.builtin.stat:
    path: "/usr/bin/gpg"
  register: gpg_stat_result

- name: "gpg - install gnupg1"
  become: true
  ansible.builtin.apt:
    pkg: gnupg1
    state: present
    update_cache: true
  register: apt
  until: "apt is not failed"
  retries: 2 # wsl1 failed first apt on Ubuntu-22.04
  when: not gpg_stat_result.stat.exists

- name: "gpg - uninstall gpg"
  become: true
  ansible.builtin.apt:
    pkg: gpg
    state: absent
    update_cache: true
  register: apt
  until: "apt is not failed"
  retries: 2 # wsl1 failed first apt on Ubuntu-22.04
  when: not gpg_stat_result.stat.exists
