# Install dotnet SDK.
# see: https://learn.microsoft.com/ja-jp/dotnet/core/install/linux-scripted-manual
#
# See below for an example of how to use this role.
# ```vars/main.yaml
# dotnet:
#   version: "7.0"
# ```
#
# ```tasks/main.yaml
# - name: ".NET - Install dotnet"
#   ansible.builtin.include_tasks: ../include_role/ubuntu/install_dotnet.yaml
#   with_items: "{{ dotnet }}"
#   loop_control:
#     loop_var: args
# ```

- name: "dotnet - check if SDK version is already installed"
  ansible.builtin.shell: "set -o pipefail && which dotnet && dotnet --list-sdks | grep '{{ args.version }}'"
  register: dotnet_check
  changed_when: false
  ignore_errors: true
  failed_when: false

- name: "dotnet - check if script file exists"
  ansible.builtin.stat:
    path: "/tmp/dotnet-install.sh"
  register: script_file
  when: dotnet_check.rc != 0

- name: "dotnet - download script"
  become: true
  ansible.builtin.get_url:
    url: "https://dot.net/v1/dotnet-install.sh"
    dest: "/tmp/dotnet-install.sh"
    mode: "a+x"
    timeout: 20
  retries: 10
  changed_when: false
  when: dotnet_check.rc != 0 and (script_file.skipped is defined or not script_file.stat.exists)

- name: "dotnet - install ({{ args.version }})"
  ansible.builtin.shell: "DOTNET_ROOT={{ ansible_home }}/.dotnet && /tmp/dotnet-install.sh --channel {{ args.version }}"
  changed_when: false
  when: dotnet_check.rc != 0
