- name: "git - Add ppa:git-core ppa repository"
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    update_cache: true

- name: "git - Install latest git"
  become: true
  ansible.builtin.apt:
    name: "git"
    state: latest
    update_cache: true
  register: apt
  failed_when: (apt.stderr == "") or '"Setting in Stop via TCSAFLUSH for stdin failed" not in apt.stdout' # for wsl1 Ubuntu-22.04
