- name: "git - Add ppa:git-core ppa repository"
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    update_cache: true

- name: "git - Install latest git"
  become: true
  ansible.builtin.apt:
    name: "git"
    state: latest
    update_cache: true
  register: apt
  until: "apt is not failed"
  retries: 2 # wsl1 failed first apt on Ubuntu-22.04
