- name: "dotfiles - create github directory"
  ansible.builtin.file:
    path: "{{ args.clone_destination }}"
    state: directory
    mode: "0755"

- name: "dotfiles - clone & Fetch"
  ansible.builtin.git:
    repo: "{{ args.repository }}"
    dest: "{{ args.clone_destination }}"

# must use shell, instead of command.
# ref: https://stackoverflow.com/questions/56989048/issue-in-ansible-playbook-command/56991314
- name: "dotfiles - create symlinks"
  become: true
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.command: "{{ args.run_command }}"
  args:
    chdir: "{{ args.clone_destination }}"
  changed_when: false
  register: install_dotfiles

- name: "dotfiles - debug show result"
  ansible.builtin.debug:
    msg: "{{ install_dotfiles.stdout_lines }}"
  when: install_dotfiles.stdout != ""

- name: "dotfiles - insert .bash_rc to load custom rc"
  ansible.builtin.blockinfile:
    create: true
    path: "{{ ansible_home }}/.bashrc"
    block: |
      if [[ -f {{ ansible_home }}/.bashrc_custom ]]; then
        source {{ ansible_home }}/.bashrc_custom
      fi
    mode: "0644"
  when: install_dotfiles is success
