# if wsl2 docker is enabled, gpg will be locate in /usr/bin/gpg
- name: "gpg - check /usr/bin/gpg exists"
  ansible.builtin.stat:
    path: "/usr/bin/gpg"
  register: gpg_stat_result

- name: "gpg - install gnupg1"
  become: true
  ansible.builtin.apt:
    pkg: gnupg1
    state: present
    update_cache: true
  register: apt
  failed_when: (apt.stderr == "") or '"Setting in Stop via TCSAFLUSH for stdin failed" not in apt.stdout' # for wsl1 Ubuntu-22.04
  when: not gpg_stat_result.stat.exists

- name: "gpg - uninstall gpg"
  become: true
  ansible.builtin.apt:
    pkg: gpg
    state: absent
    update_cache: true
  register: apt
  failed_when: (apt.stderr == "") or '"Setting in Stop via TCSAFLUSH for stdin failed" not in apt.stdout' # for wsl1 Ubuntu-22.04
  when: not gpg_stat_result.stat.exists
