- name: "git - Add ppa:git-core ppa repository"
  become: true
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: true

- name: "git - Install latest git"
  become: true
  ansible.builtin.apt:
    name: "git"
    state: latest
    update_cache: true
