# TODO: change tfenv to asdf.
- name: "tfenv - Clone & Fetch repo"
  ansible.builtin.git:
    repo: "https://github.com/tfutils/tfenv.git"
    dest: "{{ ansible_home }}/.tfenv"

- name: "tfenv - Create symlinks"
  become: true
  ansible.builtin.file:
    src: "{{ ansible_home }}/.tfenv/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    force: "{{ terraform.force_symlink }}" # true to foce remove current and replace to symlink
  with_items:
    - terraform
    - tfenv

- name: "tfenv - check already installed"
  ansible.builtin.shell: set -o pipefail && tfenv list | grep {{ terraform.version }}
  args:
    executable: /bin/bash
  register: terraform_version
  changed_when: false
  ignore_errors: true

- name: "tfenv - install"
  ansible.builtin.command: tfenv install {{ terraform.version }}
  register: terraform_install
  changed_when: terraform_install.rc != 0
  when: terraform_version is failed

- name: "tfenv - use version {{ terraform.version }}"
  ansible.builtin.command: tfenv use {{ terraform.version }}
  register: terraform_use
  changed_when: terraform_use.rc != 0
  when: terraform_version is failed

- name: "tfenv - check installed"
  ansible.builtin.shell: set -o pipefail && tfenv list | grep {{ terraform.version }}
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  changed_when: false
  when: terraform_version is failed
