# install only wsl2 and you want use....

# prerequisites
- name: "systemd - add systemd prerequisite packages"
  become: true
  ansible.builtin.apt:
    pkg:
      - daemonize
      - dbus-user-session
      - fontconfig
    update_cache: true
  register: apt
  until: "apt is not failed"
  retries: 2 # wsl1 failed first apt on Ubuntu-22.04

# scripts
- name: "systemd - contents start-systemd-namespace script"
  become: true
  ansible.builtin.copy:
    remote_src: true
    dest: "/usr/sbin/start-systemd-namespace"
    content: |
      #!/bin/bash

      SYSTEMD_PID=$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')
      if [ -z "$SYSTEMD_PID" ] || [ "$SYSTEMD_PID" != "1" ]; then
          export PRE_NAMESPACE_PATH="$PATH"
          (set -o posix; set) | \
              grep -v "^BASH" | \
              grep -v "^DIRSTACK=" | \
              grep -v "^EUID=" | \
              grep -v "^GROUPS=" | \
              grep -v "^HOME=" | \
              grep -v "^HOSTNAME=" | \
              grep -v "^HOSTTYPE=" | \
              grep -v "^IFS='.*"$'\n'"'" | \
              grep -v "^LANG=" | \
              grep -v "^LOGNAME=" | \
              grep -v "^MACHTYPE=" | \
              grep -v "^NAME=" | \
              grep -v "^OPTERR=" | \
              grep -v "^OPTIND=" | \
              grep -v "^OSTYPE=" | \
              grep -v "^PIPESTATUS=" | \
              grep -v "^POSIXLY_CORRECT=" | \
              grep -v "^PPID=" | \
              grep -v "^PS1=" | \
              grep -v "^PS4=" | \
              grep -v "^SHELL=" | \
              grep -v "^SHELLOPTS=" | \
              grep -v "^SHLVL=" | \
              grep -v "^SYSTEMD_PID=" | \
              grep -v "^UID=" | \
              grep -v "^USER=" | \
              grep -v "^_=" | \
              cat - > "$HOME/.systemd-env"
          echo "PATH='$PATH'" >> "$HOME/.systemd-env"
          exec sudo /usr/sbin/enter-systemd-namespace "$BASH_EXECUTION_STRING"
      fi
      if [ -n "$PRE_NAMESPACE_PATH" ]; then
          export PATH="$PRE_NAMESPACE_PATH"
      fi

- name: "systemd - generate start-systemd-namespace script"
  become: true
  ansible.builtin.file:
    path: "/usr/sbin/start-systemd-namespace"
    mode: a+x

- name: "systemd - contents enter-systemd-namespace script"
  become: true
  ansible.builtin.copy:
    remote_src: true
    dest: "/usr/sbin/enter-systemd-namespace"
    content: |
      #!/bin/bash

      if [ "$UID" != 0 ]; then
          echo "You need to run $0 through sudo"
          exit 1
      fi

      SYSTEMD_PID="$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')"
      if [ -z "$SYSTEMD_PID" ]; then
          /usr/bin/daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
          while [ -z "$SYSTEMD_PID" ]; do
              SYSTEMD_PID="$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')"
          done
      fi

      echo "$(pwd)" > /tmp/cwd_path
      if [ -n "$SYSTEMD_PID" ] && [ "$SYSTEMD_PID" != "1" ]; then
          if [ -n "$1" ] && [ "$1" != "bash --login" ] && [ "$1" != "/bin/bash --login" ]; then
              exec /usr/bin/nsenter -t "$SYSTEMD_PID" -a \
                  /usr/bin/sudo -H -u "$SUDO_USER" \
                  /bin/bash -c 'set -a; source "/home/$SUDO_USER/.systemd-env"; set +a; exec bash -c '"$(printf "%q" "$@")"
          else
              exec /usr/bin/nsenter -t "$SYSTEMD_PID" -a \
                  /bin/login -p -f "$SUDO_USER" \
                  $(/bin/cat "/home/$SUDO_USER/.systemd-env" | grep -v "^PATH=")
          fi
          echo "Existential crisis"
      fi

- name: "systemd - generate enter-systemd-namespace script"
  become: true
  ansible.builtin.file:
    path: "/usr/sbin/enter-systemd-namespace"
    mode: a+x

- name: "systemd - sudoers config for systemd"
  become: true
  ansible.builtin.blockinfile:
    path: "/etc/sudoers"
    block: |
      Defaults        env_keep += WSLPATH
      Defaults        env_keep += WSLENV
      Defaults        env_keep += WSL_INTEROP
      Defaults        env_keep += WSL_DISTRO_NAME
      Defaults        env_keep += PRE_NAMESPACE_PATH
      %sudo ALL=(ALL) NOPASSWD: /usr/sbin/enter-systemd-namespace

- name: "systemd - source enter-systemd-namespace in /etc/bash.bashrc"
  become: true
  ansible.builtin.blockinfile:
    path: "/etc/bash.bashrc"
    insertafter: "System-wide"
    block: |
      # Start or enter a PID namespace in WSL2
      source /usr/sbin/start-systemd-namespace

- name: "systemd - fix login path to follow before bash login (systemd)"
  become: true
  ansible.builtin.blockinfile:
    create: true
    path: /etc/profile.d/profile_ansible_init_systemd_login.sh
    block: |
      if [[ -f /tmp/cwd_path ]]; then
        cd $(cat /tmp/cwd_path)
      fi
