# ref: https://learn.microsoft.com/ja-jp/dotnet/core/install/linux-scripted-manual
- name: "dotnet - download script"
  become: true
  ansible.builtin.get_url:
    url: "https://dot.net/v1/dotnet-install.sh"
    dest: "/tmp/dotnet-install.sh"
    mode: "a+x"
  changed_when: false

- name: "dotnet - install ({{ dotnet.version }})"
  ansible.builtin.shell: "DOTNET_ROOT={{ ansible_home }}/.dotnet && /tmp/dotnet-install.sh --channel {{ dotnet.version }}"
