# ref: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
# ref: https://github.com/ocha/ansible-role-dotnet-core
- name: "dotnet - make sure HTTPS is supported by apt"
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: true
  register: apt
  until: "apt is not failed"
  retries: 2 # wsl1 failed first apt on Ubuntu-22.04
  when: ansible_distribution_version != "22.04"

- name: "dotnet - import Microsoft apt key"
  become: true
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb"
    dest: "/tmp/packages-microsoft-prod.deb"
    mode: "0644"
  changed_when: false
  when: ansible_distribution_version != "22.04"

- name: "dotnet - add repo for Ubuntu"
  become: true
  ansible.builtin.command: dpkg -i /tmp/packages-microsoft-prod.deb
  register: dotnet_add_repo
  changed_when: dotnet_add_repo.rc != 0
  when: ansible_distribution_version != "22.04"

- name: "dotnet - install ({{ dotnet.version }})"
  become: true
  ansible.builtin.package:
    name: "{{ dotnet.version }}"
    state: present
    update_cache: true
