# ref: https://aquasecurity.github.io/trivy/v0.18.2/installation/
- name: "trivy - make sure HTTPS is supported by apt"
  become: true
  ansible.builtin.apt:
    pkg:
      - wget
      - apt-transport-https
      # - gnupg # want to skip....
      - lsb-release
    state: present
    update_cache: true
  register: apt
  failed_when: (apt.stderr == "") or '"Setting in Stop via TCSAFLUSH for stdin failed" not in apt.stdout' # for wsl1 Ubuntu-22.04

- name: "trivy - import apt key"
  become: true
  ansible.builtin.apt_key:
    url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    state: present

- name: "trivy - add repo for Ubuntu"
  become: true
  ansible.builtin.shell: set -o pipefail && echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
  args:
    executable: /bin/bash
  changed_when: false

- name: "trivy - install trivy"
  become: true
  ansible.builtin.package:
    name: trivy
    state: latest
    update_cache: true
