# docker
# if wsl2 docker is enabled, docker will be locate in /usr/bin/docker
# to use this spec, you must disable docker run on wsl but run on Hyper-V instead.
# then install docker on your Ubuntu.
- name: "docker - make sure install prerequisites"
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: true

- name: "docker - import Docker apt key"
  become: true
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  args:
    warn: false
  changed_when: false

- name: "docker - add repo for Ubuntu"
  become: true
  apt_repository:
    # $(lsb_release -cs) = {{ ansible_distribution_release }}
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: true

# note: remove old version when error occured: `sudo apt-get remove docker docker-engine docker.io containerd runc`
- name: "docker - install"
  become: true
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - cgroupfs-mount
    update_cache: true

# docker service daemon for SysV Init
- name: "docker - startup profile.d script (wsl1)"
  become: true
  blockinfile:
    create: true
    path: /etc/profile.d/profile_ansible_init_docker.sh
    block: |
      sudo -S cgroupfs-mount
      sudo usermod -aG docker $USER
      sudo service docker start
      # wsl1 using windows docker-compose. wsl2 don't need this line.
      export DOCKER_HOST=tcp://localhost:2375
  when: args.require_sysvinit == "1"
