- name: "tfenv - Clone & Fetch repo"
  ansible.builtin.git:
    repo: "https://github.com/tfutils/tfenv.git"
    dest: "{{ ansible_home }}/.tfenv"

- name: "tfenv - Create symlinks"
  become: true
  ansible.builtin.file:
    src: "{{ ansible_home }}/.tfenv/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - terraform
    - tfenv

- name: "tfenv - check installed"
  ansible.builtin.shell: set -o pipefail && tfenv list | grep {{ args.version }}
  args:
    executable: /bin/bash
  register: terraform_version
  changed_when: false
  ignore_errors: true

- name: "tfenv - install"
  ansible.builtin.command: tfenv install {{ args.version }}
  when: terraform_version is failed

- name: "tfenv - use version {{ args.version }}"
  ansible.builtin.command: tfenv use {{ args.version }}
  when: terraform_version is failed
