# TODO: change to asdf.
# aws2
# install to /usr/local/aws by default.
# symlink to /usr/local/bin/aws by default.
- name: "awscli - check exists"
  ansible.builtin.shell: set -o pipefail && aws --version 2>&1 | head -n 1 | grep "aws-cli/{{ args.version }}"
  args:
    executable: /bin/bash
  register: awscli_exists
  changed_when: false
  ignore_errors: true

- name: "awscli - download"
  ansible.builtin.command: curl -L "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ aws_cli.version }}.zip" -o /tmp/awscliv2.zip
  register: awscli_download
  changed_when: awscli_download.rc != 0
  when: awscli_exists is failed

- name: "awscli - unzip"
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true
  when: awscli_exists is failed

- name: "awscli - install"
  become: true
  ansible.builtin.command: /tmp/aws/install --update
  register: awscli_install
  changed_when: awscli_install.rc != 0
  when: awscli_exists is failed

- name: "awscli - clean up tmp zip"
  ansible.builtin.file:
    path: /tmp/awscliv2.zip
    state: absent
  when: awscli_exists is failed
