- name: local-dev ubuntu setup
  hosts: "local"
  pre_tasks:
    - name: Preset ansible_home as execution user HOME path
      ansible.builtin.set_fact: ansible_home='{{ ansible_env.HOME }}'
      tags: always
    - name: Get WSL1
      ansible.builtin.shell: set -o pipefail && grep "Microsoft" /proc/version | wc -l
      register: wsl1_exists
      changed_when: false
      check_mode: false
      tags: always
    - name: Preset WSL1 or not
      ansible.builtin.set_fact: is_wsl1='{{ wsl1_exists.stdout }}'
      tags: always
    - name: Get WSL2
      ansible.builtin.shell: set -o pipefail && grep "microsoft-standard" /proc/version | wc -l
      register: wsl2_exists
      changed_when: false
      check_mode: false
      tags: always
    - name: Preset WSL2 or not
      ansible.builtin.set_fact: is_wsl2='{{ wsl2_exists.stdout }}'
      tags: always
  roles:
    - { role: "debug", tags: [debug] }
    - { role: "dotfiles", tags: [dotfiles] }
    - { role: "credentials", tags: [credentials] }
    - { role: "needrestart", tags: [needrestart] }
    - { role: "docker", tags: [docker], when: is_wsl2 == "1" }
    - { role: "tools", tags: [tools] }
