- name: local-dev ubuntu setup
  hosts: "local"
  pre_tasks:
    - name: Preset ansible_home as execution user HOME path
      ansible.builtin.set_fact:
        ansible_home: "{{ ansible_env.HOME }}"
      tags: always
    - name: Detect WSL version
      ansible.builtin.command: uname -r
      register: kernel_version
      tags: always
    - name: Set is_wsl2 variable
      set_fact:
        is_wsl2: "{{ 'WSL2' in kernel_version.stdout or 'microsoft-standard' in kernel_version.stdout }}"
      tags: always
    - name: Set is_wsl1 variable
      set_fact:
        is_wsl1: "{{ 'Microsoft' in kernel_version.stdout }}"
      tags: always
  roles:
    - { role: "debug", tags: [debug] }
    - { role: "dotfiles", tags: [dotfiles] }
    - { role: "credentials", tags: [credentials] }
    - { role: "needrestart", tags: [needrestart] }
    - { role: "docker", tags: [docker] }
    - { role: "tools", tags: [tools] }
