- name: local-dev ubuntu setup
  hosts: "local"
  become: no
  pre_tasks:
    - name: Get ansible_user home directory
      become: no
      shell: "getent passwd {{ ansible_user_id }} | cut -d: -f6"
      register: ansible_home_result
      changed_when: false
      check_mode: no
      tags: always
    - name: Set the fact for the other scripts to use
      set_fact: ansible_home='{{ ansible_home_result.stdout }}'
  roles:
    - { role: "debug", tags: [debug] }
    - { role: "dotfiles", tags: [dotfiles] }
    - { role: "tools", tags: [tools] }
    - { role: "yq", tags: [yq] }
    - { role: "awscli", tags: [awscli] }
    - { role: "azcli", tags: [azcli] }
    - { role: "terraform", tags: [terraform] }
    - { role: "docker", tags: [docker] }
    - { role: "circleci", tags: [circleci] }
    - { role: "ngrok", tags: [ngrok] }
    - { role: "kubernetes", tags: [kubernetes] }
    - { role: "dotnetsdk", tags: [dotnetsdk] }
    - { role: "envsubst2", tags: [envsubst2] }
# ansible-playbook -i hosts site.yml --ask-become-pass
