- name: local-dev ubuntu setup
  hosts: "local"
  become: no
  pre_tasks:
    - name: Preset ansible_home as execution user HOME path
      set_fact: ansible_home='{{ lookup('env','HOME') }}'
    - name: Get WSL1 or WSL2
      become: no
      shell: cat /proc/version | grep Microsoft | wc -l
      register: wsl1_exists
      changed_when: false
      check_mode: no
      tags: always
    - name: Preset WSL1 or not
      set_fact: is_wsl1='{{ wsl1_exists.stdout }}'
  roles:
    - { role: "debug", tags: [debug] }
    - { role: "dotfiles", tags: [dotfiles] }
    - { role: "credentials", tags: [credentials], when: is_wsl1 == "0" } # when wsl2
    - { role: "gpg", tags: [gpg], when: is_wsl1 == "1" } # when wsl1
    - { role: "tools", tags: [tools] }
    - { role: "yq", tags: [yq] }
    - { role: "awscli", tags: [awscli] }
    - { role: "terraform", tags: [terraform] }
    - { role: "pulumi", tags: [pulumi] }
    - { role: "circleci", tags: [circleci] }
    - { role: "ngrok", tags: [ngrok] }
    - { role: "dotnetsdk", tags: [dotnetsdk] }
    #- { role: "systemd", tags: [systemd], when: is_wsl1 == "0" }
    - { role: "docker", tags: [docker] }
    - { role: "kubernetes", tags: [kubernetes] }
