- name: local-dev ubuntu setup
  hosts: "local"
  become: no
  pre_tasks:
    - name: Set ansible_home as execution user.
      set_fact: ansible_home='{{ lookup('env','HOME') }}'
  roles:
    - { role: "debug", tags: [debug] }
    - { role: "dotfiles", tags: [dotfiles] }
    - { role: "tools", tags: [tools] }
    - { role: "bombardier", tags: [bombardier] }
    - { role: "yq", tags: [yq] }
    - { role: "awscli", tags: [awscli] }
    - { role: "azcli", tags: [azcli] }
    - { role: "terraform", tags: [terraform] }
    - { role: "pulumi", tags: [pulumi] }
    #- { role: "docker", tags: [docker] }
    - { role: "circleci", tags: [circleci] }
    - { role: "ngrok", tags: [ngrok] }
    - { role: "kubernetes", tags: [kubernetes] }
    - { role: "dotnetsdk", tags: [dotnetsdk] }
    - { role: "envsubst2", tags: [envsubst2] }
# ansible-playbook -i hosts site.yml --ask-become-pass
