- name: local-dev ubuntu setup
  hosts: "local"
  become: no
  pre_tasks:
    - name: Preset ansible_home as execution user HOME path
      set_fact: ansible_home='{{ lookup('env','HOME') }}'
      tags: always
    - name: Get WSL2
      shell: cat /proc/version | grep microsoft-standard | wc -l
      register: wsl2_exists
      changed_when: false
      check_mode: no
      tags: always
    - name: Preset WSL2 or not
      set_fact: is_wsl2='{{ wsl2_exists.stdout }}'
      tags: always
  roles:
    - { role: "debug", tags: [debug] }
    - { role: "dotfiles", tags: [dotfiles] }
    - { role: "credentials", tags: [credentials] }
    - { role: "tools", tags: [tools] }
    - { role: "docker", tags: [docker], when: is_wsl2 == "0" }
