# https://github.com/lukesampson/scoop/tree/master/bucket
- name: "Install linux tools"
  scoop_install:
    state: present
    name:
      - cmake
      - jq
      - sudo

- name: "Install windows tools"
  scoop_install:
    state: present
    name:
      - pwsh
      - terraform
      - gibo

- name: "Install Programming Languages"
  scoop_install:
    state: present
    name:
      - go
      - nvm
