---
- name: Clone & Fetch dotfiles
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items: "{{ repository }}"
  when: repository is defined

- name: Create symlinks
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ symlink }}"
  when: repository is defined

- name: pickup installed terraform versions
  shell: tfenv list | grep {{ version }}
  register: terraform_version
  changed_when: false
  ignore_errors: yes

- name: install terraform
  command: tfenv install {{ version }}
  register: terraform
  when: terraform_version is failed

- debug: msg="{{ terraform.stdout_lines }}"
  when: terraform is failed
