---

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes

- name: apt-get install azcli
  become: yes
  apt:
    pkg: [
      unzip,
    ]
    state: present
    update_cache: yes

- name: Clone & Fetch dotfiles
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items: "{{ repository }}"
  when: repository is defined

- name: Create symlinks
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ symlink }}"
  when: repository is defined

- name: install terraform
  command: tfenv install {{ version }}
  register: terraform

- debug: msg="{{ terraform.stdout_lines }}"
