---
- name: "{{ ansible_role_name}}: Clone & Fetch repo"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items: "{{ repository }}"
  when: repository is defined

- name: "{{ ansible_role_name}}: Create symlinks"
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ symlink }}"
  when: repository is defined

- name: "{{ ansible_role_name}}: check installed"
  shell: tfenv list | grep {{ version }}
  register: terraform_version
  changed_when: false
  ignore_errors: yes

- name: "{{ ansible_role_name}}: install"
  command: tfenv install {{ version }}
  register: terraform
  when: terraform_version is failed

- name: "{{ ansible_role_name}}: use version {{ version }}"
  command: tfenv use {{ version }}
  register: terraform
  when: terraform_version is failed

- name: "{{ ansible_role_name}}: version"
  debug:
    msg: "{{ terraform.stdout_lines }}"
  when: terraform is failed
