---

- name: Create github directory
  file:
    path: "{{ base_path }}"
    state: directory

- name: Clone dotfiles
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items: "{{ repository }}"

- name: Create symlinks
  command: bash -lc "{{ run_dotfiles }}"
  changed_when: False
  register: dotfiles

- debug: msg="{{ dotfiles.stdout_lines }}"