- name: Create github directory
  ansible.builtin.file:
    path: "{{ base_path }}"
    state: directory
    force: true
    mode: "0755"

- name: Clone dotfiles
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    force: true
  with_items: "{{ repository }}"

- name: Create symlinks
  ansible.builtin.command: bash -lc "{{ run_dotfiles }}"
  register: dotfiles_install
  changed_when: dotfiles_install.rc != 0

- name: "Debug show result"
  ansible.builtin.debug:
    msg: "{{ dotfiles_install.stdout_lines }}"
  when: dotfiles_install.stdout != ""
