docker_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
docker_repo_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_pkgs:
  - docker-ce
  - docker-ce-cli
  - containerd.io
