docker_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
docker_pkgs:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - cgroupfs-mount
dockercompose_version: 1.27.4
