name: install

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/install.yaml"
      - "envs/**/*"

env:
  TERM: xterm

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
        working-directory: envs/ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Install ansible
        run: sudo apt update && sudo apt install -y ansible
      - name: ansible version
        run: ansible --version
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 1st Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 2nd Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff

  macos:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-15, macos-14]
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
        working-directory: envs/macos
    steps:
      - uses: actions/checkout@v4
      - name: Install ansible
        run: brew install ansible
      - name: ansible version
        run: ansible --version
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 1st Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 2nd Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff

  windows:
    runs-on: windows-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: powershell
        working-directory: envs/windows
    steps:
      - uses: actions/checkout@v4
      - uses: MinoruSekine/setup-scoop@main # use @main to fix. see https://github.com/MinoruSekine/setup-scoop/issues/7
      - name: scoop version
        run: scoop --version
      - name: Install Modules
        run: |
          Install-Module PowerShell-Yaml -Force -Scope CurrentUser
          Install-Module ScoopPlaybook -Force -Scope CurrentUser
      - name: 1st Run ScoopPlaybook
        run: Scoop-Playbook
      - name: 2nd Run ScoopPlaybook
        run: Scoop-Playbook
