name: install

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/install.yaml"
      - "envs/**/*.yaml"

env:
  TERM: xterm

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
        working-directory: envs/ubuntu
    steps:
      - uses: actions/checkout@v3
      - name: Install ansible
        run: pip3 install ansible
      - name: Run Ansible Playbook
        run: . ./install.sh
