name: install

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/install.yaml"
      - "envs/**/*"

env:
  TERM: xterm

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu] # todo: macOS and Windows
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
        working-directory: envs/${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install ansible
        run: pip3 install ansible
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 1st Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 2nd Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
