name: install

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/install.yaml"
      - "envs/**/*"

env:
  TERM: xterm

jobs:
  ansible:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos] # todo: Windows
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 45
    defaults:
      run:
        shell: bash
        working-directory: envs/${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install ansible
        run: pip3 install ansible
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 1st Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 2nd Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff

  scoop:
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: powershell
        working-directory: envs/${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: MinoruSekine/setup-scoop@main # use @main to fix. see https://github.com/MinoruSekine/setup-scoop/issues/7
      - name: Test Scoop installed
        run: scoop --version
      - name: Install Modules
        run: |
          Install-Module PowerShell-Yaml -Force -Scope CurrentUser
          Install-Module ScoopPlaybook -Force -Scope CurrentUser
      - name: 1st Run ScoopPlaybook
        run: Scoop-Playbook
      - name: 2nd Run ScoopPlaybook
        run: Scoop-Playbook
