name: install

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: null
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/install.yaml"
      - "envs/**/*"

env:
  TERM: xterm

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: write
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
        working-directory: envs/ubuntu
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install ansible
        run: sudo apt update && sudo apt install -y ansible
      - name: ansible version
        run: ansible --version
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 1st Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 2nd Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff

  macos:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-15, macos-14]
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: write
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
        working-directory: envs/macos
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install ansible
        run: brew install ansible
      - name: ansible version
        run: ansible --version
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 1st Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff
      - name: 2nd Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml
      - name: (Dryrun) Run Ansible Playbook
        run: ansible-playbook -i hosts playbook.yaml --check --diff

  windows:
    runs-on: windows-latest
    timeout-minutes: 20
    permissions:
      contents: write
    defaults:
      run:
        shell: powershell
        working-directory: envs/windows
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: MinoruSekine/setup-scoop@80f7f261b2e62af5d7450c85317b194046aa91f5 # v4.0.1

      - name: scoop version
        run: scoop --version
      - name: Install Modules
        run: |

          Install-Module PowerShell-Yaml -Force -Scope CurrentUser
          Install-Module ScoopPlaybook -Force -Scope CurrentUser

      - name: 1st Run ScoopPlaybook
        run: Scoop-Playbook
      - name: 2nd Run ScoopPlaybook
        run: Scoop-Playbook
